### ISSUE TITLE
[NEW FEATURE] : Multi-Camera Mars Rover Image Viewer

### ISSUE THREAD

**Issue by shubhanshukaintura** [PranavBarthwal/cosmoXplore#106]
### Describe the feature

To make a comprehensive view of the Martian landscape I suggest implementing a multi-camera Mars rover image viewer. This feature will enable users to access and view images captured by various cameras aboard the Mars rovers, providing a richer and more diverse perspective of the Red Planet.

### It should be implemented because

1. Diverse Perspectives: Each camera on the Mars rover captures unique views and details of the Martian surface.

2. Enhanced Exploration: Providing access to multiple Mars rover images from different cameras will enrich the exploration experience for users, allowing them to gain a more comprehensive understanding of the Martian terrain and environment.

### Additional context

I would like to implement this New Feature
Please assign this repo under GSSOC 24....

### Would you like to work on this issue?

Yes

**Comment by PranavBarthwal** [comment]
Go ahead
