### ISSUE TITLE
Adding star parallax effect animation on background

### ISSUE THREAD

**Issue by achlbatra** [PranavBarthwal/cosmoXplore#108]
### Describe the feature

As the site is related to space, I would like to add a parallax effect on the background to enhance the UI

### Additional context

Please assign me this issue under GSSoC'24

### Would you like to work on this issue?

Yes

**Comment by PranavBarthwal** [comment]
Can you provide some video for the same?

**Comment by achlbatra** [comment]
Here is a sample video of a project I contributed for the same:


https://github.com/PranavBarthwal/cosmoXplore/assets/157528686/b5295aaf-a40d-4948-9631-af562b70d80d

**Comment by PranavBarthwal** [comment]
a similar effect is already present on the website!
