### ISSUE TITLE
Automated Greeting Workflow

### ISSUE THREAD

**Issue by sanmarg** [PranavBarthwal/cosmoXplore#110]
### Describe the feature

I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository.  The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible."

Please assign this issue to me

### Additional context

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/50082154/e4a3c02b-44bd-4352-a4d0-58f3a7d2a969)

### Would you like to work on this issue?

Yes

**Comment by PranavBarthwal** [comment]
Go ahead

**Comment by sanmarg** [comment]
Task done.
