### ISSUE TITLE
Typos in source code

### ISSUE THREAD

**Issue by Chandu6702** [PranavBarthwal/cosmoXplore#114]
### Describe your issue

There are a few typos in the source code and issues template which take a lot of time to find and resolve, and it doesn't follow the proper naming convention.

### Steps to reproduce the bug

1. Go to line number 136,138 in index.html.
2. Go to line number 16 in doc_report.yml
3. we can find the typos there.

### Put here any screenshots or videos (optional)

![Screenshot 2024-05-13 121510](https://github.com/PranavBarthwal/cosmoXplore/assets/125206920/1c352ec4-2b1f-4730-84d8-ba116587e382)

![Screenshot 2024-05-13 121440](https://github.com/PranavBarthwal/cosmoXplore/assets/125206920/d5fdc99d-219a-4d51-a31c-434e2d2c7ec2)

![Screenshot 2024-05-13 124638](https://github.com/PranavBarthwal/cosmoXplore/assets/125206920/148d5ee2-e55a-4fff-8f2c-1f589c6406de)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I can review all the source code and documentation to find and resolve typos.

**Comment by PranavBarthwal** [comment]
go ahead
