### ISSUE TITLE
about conatct us hover box

### ISSUE THREAD

**Issue by Reshma-2301** [PranavBarthwal/cosmoXplore#116]
### Describe the feature

hello sir @PranavBarthwal . i have visited your website and i found that only conatct us option has that effect and other section like home etc does not ...i would suggest you to either remove all the effect and all the effect ..by adding only effect on conatct us  makes ugly ..it is not soothing ... 

![effect](https://github.com/PranavBarthwal/cosmoXplore/assets/162494882/f6a1f57b-e307-401b-9f38-c6861eb3e49c)

### It should be implemented because
it should be implemented because it will enhace the overall look of website 

### Additional context

i would request you to assign me that task i would remove that effect from conatct us 
please @PranavBarthwal assign that enhancement issue to me 

### Would you like to work on this issue?

Yes

**Comment by PranavBarthwal** [comment]
Duplicate issue. 
Someone's already workking on it
