### ISSUE TITLE
Add Loader Animation to Mars Rover Display Section during API call

### ISSUE THREAD

**Issue by DonaldReddy** [PranavBarthwal/cosmoXplore#117]
### Describe the feature

Adding Loader animation to Mars Rover Display section during API call which matches the website theme.

this is the loader I would like to add 👇

https://github.com/PranavBarthwal/cosmoXplore/assets/83972294/000f5077-61a8-4d96-85a1-69abc6a997e6

### It should be implemented because

Adding Loader animation during API calls improves the user experience.

### Additional context

I can also add this loader to the APoD section.

Please assign this issue to me @PranavBarthwal 

### Would you like to work on this issue?

Yes

**Comment by PranavBarthwal** [comment]
Go ahead! @DonaldReddy

**Comment by DonaldReddy** [comment]
@surajvast1 can i start working on this ?

**Comment by surajvast1** [comment]
Yeah @PranavBarthwal
