### ISSUE TITLE
Changing the UI of date picker

### ISSUE THREAD

**Issue by divyalaldinani** [PranavBarthwal/cosmoXplore#118]
### Describe the feature

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/82147067/c76dfbf1-47a2-432a-9212-9f3854cde9ac)
adjusting the padding, the placeholder text and changing the theme of input field and button to get it aligned with page's theme.

### It should be implemented because

to maintain the theme and overall appearance of web page.

### Would you like to work on this issue?

YES

**Comment by PranavBarthwal** [comment]
Duplicate issue. someone is already working on this
Please check other issues before raising your own.
