### ISSUE TITLE
Sticky NavBar

### ISSUE THREAD

**Issue by girish-07** [PranavBarthwal/cosmoXplore#12]
### Describe the feature

NavBar displayed in the site is not fixed at the top of the page. So, we have to make it stick at the top of the page, so, even though we navigate across the sections, it is still on top

### It should be implemented because

It will allow us to navigate to any section of the page from anywhere in the page.

### Additional context

For example, if we have to reach the Mars page from the Contact page, we need to scroll up at present, but with sticky NavBar, we could reach the section with just a click

### Would you like to work on this issue?

Yes

**Comment by VedantAnand17** [comment]
I can help and am well experienced in web development and have made several projects in it. Kindly assign this issue to me.

**Comment by Adi-gitX** [comment]
Issue:
The website's navigation bar (NavBar) is not stationary at the top of the page. Consequently, when users move across different sections of the website, they are required to scroll back to the top to access the navigation menu. 

Solution:
To provide a better user experience, a sticky NavBar feature should be implemented. This feature will keep the NavBar fixed at the top of the page, ensuring easy access to the navigation menu from any part of the website. e.

i would like to solve this issue by adding requred css in navbar, please assign me this issue

**Comment by PranavBarthwal** [comment]
@girish-07 Thanks for raising this issue.
I'll surely assign this to you after 19:00 so that it gets counted under GSSoC'24.

**Comment by Adi-gitX** [comment]
Thank you. I will start working on it.

**Comment by shaurya35** [comment]
Hi @PranavBarthwal

I've addressed this issue with `Sticky Navigation Menu Bar.`

`**Opened a pull request for the same.**`

Pull Request #15 

Looking forward to the opportunity to work together on this project.

Best regards,
Shaurya
(GSSOC Contributor)

**Comment by PranavBarthwal** [comment]
Hi @shaurya35, the issues are assigned on first come basis and you are requested to start working and submit a PR only if you are assigned an issue. So this PR cant be merged.
Thanks

**Comment by shaurya35** [comment]
Hi @PranavBarthwal 

`Thank you for clarifying, I will keep those things in mind while contributing next.`

I have created another issue regarding the UI. Feedbacks are appreciated.

Happy to collaborate for more features and implementation.

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me
@PranavBarthwal
