### ISSUE TITLE
Upgrade Appearance of Contact Form and Date Field

### ISSUE THREAD

**Issue by SamarupBhattacharya** [PranavBarthwal/cosmoXplore#125]
### Describe the feature

I want to provide background color change, border-radius change and font-family change for the Contact Us form and Date field as well as add animation effects to them which will make them at par with the visual standards of the rest of the website

### It should be implemented because

The changes will make the Contact Us form and the Date field appear like they are a part of amazingly designed website and it will make them stop standing out as they are now.

### Additional context

The website is obviously amazing but I feel like the simple looking Contact Us form and the Date field don't do justice to the rest of the website. I will like to come in here and fix it, please do assign it to me and attach the labels of **gssoc** and **level 1** or **level 2** to this.
![2024-05-13-18-44-09](https://github.com/PranavBarthwal/cosmoXplore/assets/138982308/48a19154-f73c-4272-932b-c15d077c1cff)
![2024-05-13-18-44-31](https://github.com/PranavBarthwal/cosmoXplore/assets/138982308/961c0686-4906-440c-82c7-2942f3171f9a)

### Would you like to work on this issue?

Yes

**Comment by PranavBarthwal** [comment]
#40 
already assigned to someone else. 
Please check other issues before creating your own to avoid duplicates.
