### ISSUE TITLE
Improve Navigation-Menu and Typewriter Effect

### ISSUE THREAD

**Issue by shaurya35** [PranavBarthwal/cosmoXplore#13]
Hi @PranavBarthwal 

I've been following up with the progress of cosmoXplore and I'm impressed with what you've accomplished so far!
I believe I can offer valuable insights and contributions to help elevate the user experience. For that I have `improved the Navigation Menu and the typewriter Effect.
`

Opened a pull request for the same. 

Looking forward to the opportunity to work together on this project.

Best regards,
Shaurya
(GSSOC Contributor)

**Comment by shaurya35** [comment]
Pull Request #14 
`Make sure to check it out and let me know about the feedback.`

Happy to contribute more.

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me
@PranavBarthwal
