### ISSUE TITLE
[Doc]:  Add Latest Image of Landing Page in  Readme

### ISSUE THREAD

**Issue by DonaldReddy** [PranavBarthwal/cosmoXplore#131]
### Describe the bug

- [X] Information addition regarding the newest change through a PR.
- [ ] Typo error.
- [ ] New category addition.
- [ ] Refractoring sentences that make more sense.
- [ ] Fixing broken links.
- [ ] Refractors / reformating of the document.

### Additional Context

With the recent UI changes made to the Landing Page, the latest image of the Landing Page should be added to the Readme file.

![home](https://github.com/PranavBarthwal/cosmoXplore/assets/83972294/572d5a58-5fdd-47ef-899e-e65f1c0de0eb)

**Comment by Seba-Aguero** [comment]
Hi! Could you assign me this issue?

**Comment by Yuvraj960** [comment]
@PranavBarthwal Please assign this issue to me under GSSoC24
