### ISSUE TITLE
UI enhancement - The page is not responsive 

### ISSUE THREAD

**Issue by sharmi4590** [PranavBarthwal/cosmoXplore#155]
### Describe your issue

The page is not responsive

### Steps to reproduce the bug

I will add some bootstrap features to make the page responsive.

### Put here any screenshots or videos (optional)

![Screenshot_20240514-220101](https://github.com/PranavBarthwal/cosmoXplore/assets/102676949/15444e7c-06f1-45a0-ad9b-2d948c46dc47)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I will add Better CSS and bootstrap .

**Comment by TechSavvyDivyansh** [comment]
I want to work on this issue .Please assign it to me . It can be sorted easily by making changes in some parts of stylesheet.
