### ISSUE TITLE
Page to Show Latest Technology Made at NASA

### ISSUE THREAD

**Issue by DonaldReddy** [PranavBarthwal/cosmoXplore#157]
### Describe the feature

A Page dedicated to showing the latest technology projects Happening at NASA by using NASA's Techport API.

This page shows the latest Projects happening seven days before the current date.

It will keep on going back seven days till it finds the latest projects to show.

### It should be implemented because

By implementing this feature users can stay updated on the latest Projects happening at NASA.

### Additional context

please assign this issue to me @PranavBarthwal

### Would you like to work on this issue?

Yes

**Comment by DonaldReddy** [comment]
Hey @surajvast1 as the project has successfully migrated into React, can you please assign this issue to me?

**Comment by DonaldReddy** [comment]
Thanks @surajvast1 😁

**Comment by surajvast1** [comment]
Update??

**Comment by DonaldReddy** [comment]
@surajvast1 I'll work on this issue after the pr for project structure is merged. So that no merge conflict will occur 😁

**Comment by DonaldReddy** [comment]
Or should I start working on it assuming that project structure pr will be merged?

**Comment by DonaldReddy** [comment]
Hey @PranavBarthwal,
I am unable to do API call to `https://techport.nasa.gov/api/projects?updatedSince=2024-05-01&api_key=eISHzmGbQk7EMWv9NTlVtvzZVmeLKPUoL3uKMSPJ` due to cors policy

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/83972294/a980f78d-0eff-4947-929c-77a1c45469a8)

**Comment by DonaldReddy** [comment]
I think the only way to overcome this is by having our own proxy server.
