### ISSUE TITLE
Footer Page Styling & Redirection Issue

### ISSUE THREAD

**Issue by SHARITHA2002** [PranavBarthwal/cosmoXplore#16]
Hi,

I hope this message finds you well. I've been impressed with the CosmoXplore website. However, I noticed an issue regarding the page redirection in the footer while clicking the logo that I believe needs attention.  Additionally, I would like to offer my assistance in styling the footer to enhance its visual appeal and usability.

**Issue Description:**

When clicking the logo in the footer, the page redirection behaves unexpectedly, redirection to the wrong page.

**Expected Behavior:**

The logo in the footer should redirect users to the homepage.

**Current Behavior:**

Upon clicking the logo in the footer, the redirection leads to a 404 error page.

In addition to addressing this issue, I would like to contribute by styling the footer to improve its overall appearance and user experience.

Would it be possible for you to assign me this issue? I'm eager to collaborate and help improve the CosmoXplore website.

Looking forward to your response.

Best regards,
Sharitha G
(GSSOC'24 Contributor)

**Comment by arifakhtar51** [comment]
Hello @PranavBarthwal can i work on this ??
i'm a GSSOC'24 Contributor

**Comment by PranavBarthwal** [comment]
> Hello @PranavBarthwal can i work on this ??
> i'm a GSSOC'24 Contributor

Hi @arifakhtar51 this issue is already assigned to @SHARITHA2002.
You can raise another issue to work on.
Happy Coding.

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me
@PranavBarthwal
