### ISSUE TITLE
[Doc]: calendar date not visible!

### ISSUE THREAD

**Issue by Anjaliavv51** [PranavBarthwal/cosmoXplore#168]
### Describe the bug

- [X] Information addition regarding the newest change through a PR.
- [ ] Typo error.
- [X] New category addition.
- [ ] Refractoring sentences that make more sense.
- [ ] Fixing broken links.
- [ ] Refractors / reformatting of the document.

### Additional Context
Before changes:
![Screenshot (182)](https://github.com/PranavBarthwal/cosmoXplore/assets/154777864/d84f9ad1-f358-4b2c-be4c-400439238a13)

After Changes:

![Screenshot 2024-05-15 230740](https://github.com/PranavBarthwal/cosmoXplore/assets/154777864/037048df-71e0-49b3-91f7-a9cc09eba1c4)

**Comment by PranavBarthwal** [comment]
go ahead

**Comment by Anjaliavv51** [comment]
![Screenshot (181)](https://github.com/PranavBarthwal/cosmoXplore/assets/154777864/d46aea9c-9a1d-4391-ab6b-2fa6700b91c3)
