### ISSUE TITLE
Issue in calendar 

### ISSUE THREAD

**Issue by kapilG0** [PranavBarthwal/cosmoXplore#178]
### Describe the feature

Issue in calendar 
![Screenshot_20240516_133223](https://github.com/PranavBarthwal/cosmoXplore/assets/59639410/a9dad7d6-3db4-44fb-a726-4d6b471bfeda)

### Would you like to work on this issue?

Yes

**Comment by kapilG0** [comment]
Hello @PranavBarthwal please assign this issue to me under gssoc 24

**Comment by harshit-sharmaaa** [comment]
what's the issue. write proper explaination

**Comment by harshit-sharmaaa** [comment]
someone else is working on it
