### ISSUE TITLE
Add a Favicon to cosmoXplore Website

### ISSUE THREAD

**Issue by SHARITHA2002** [PranavBarthwal/cosmoXplore#18]
**Title:**

Add Logo to Address Bar of Website

**Describe the feature:**

A logo should be added to the address bar of the website to enhance its branding and visual identity. This logo will appear next to the website's URL in the browser's address bar and tabs, providing a consistent visual representation of the website to users.

**Current Behavior:**

The website currently lacks a logo in the address bar, as depicted in the screenshot below:

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/100562754/cda3cfe9-3a4e-495b-afcb-5033b6958ed2)

I'm willing to assist with this feature. If you agree with this proposal, I would be happy to collaborate and help make this enhancement a reality.

Looking forward to your feedback and the opportunity to contribute to the improvement of the cosmoXplore website.

Best regards,
Sharitha G
GSSOC'24 Contributor

**Comment by PranavBarthwal** [comment]
@SHARITHA2002 you are already assigned one issue, once you submit a PR for that issue only then I can assign you another.

Also you are requested to use the existing templates for issue creation.
![Screenshot 2024-05-11 131846](https://github.com/PranavBarthwal/cosmoXplore/assets/110532770/c1a36e45-43e9-4ed7-b8ee-f839a99b3653)

**Comment by PranavBarthwal** [comment]
@divyalaldilani assigned to you

**Comment by SHARITHA2002** [comment]
Got it! I'll make sure to submit the PR for the assigned issue before requesting another. I'll also use the existing templates for issue creation. Thanks for the clarification!
