### ISSUE TITLE
enter date by selecting from calender

### ISSUE THREAD

**Issue by paulkrishanu4** [PranavBarthwal/cosmoXplore#19]
### Describe the feature

I want to improve the input format of date like this

<img width="242" alt="image" src="https://github.com/PranavBarthwal/cosmoXplore/assets/169196836/108b01df-1eef-4ed0-8ae4-f8cc32da3e6c">

### It should be implemented because

looks good

### Would you like to work on this issue?

Yes

**Comment by PranavBarthwal** [comment]
Good issue @paulkrishanu4, go ahead. Assigned to you.
Additionally,  make sure that the user can only enter a date that falls between January 2024 and January 2019.
