### ISSUE TITLE
Feature: Adding a custom scrollbar

### ISSUE THREAD

**Issue by Madhuri36** [PranavBarthwal/cosmoXplore#195]
### Describe the feature

**Custom Scrollbar**
- Stylish Design: The scrollbar is redesigned to match the aesthetic of the webpage, offering a more modern and integrated look.
- Hover Effects: Includes hover effects to provide visual feedback to the user when interacting with the scrollbar.
- Cross-Browser Compatibility: Ensures consistent appearance and functionality across all major browsers.

### It should be implemented because

I want to add a custom Scroll bar so that it can match with the website's UI.
@PranavBarthwal please assign this to me under GSSoC'24

### Would you like to work on this issue?

Yes

**Comment by harshit-sharmaaa** [comment]
add screenshots for better understanding

**Comment by Madhuri36** [comment]
@harshit-sharmaaa something like this:

![Screenshot_20240519_175600_Google.jpg](https://github.com/PranavBarthwal/cosmoXplore/assets/146222028/b5939874-356c-43a3-9aed-96e1cca9f3b0)

I can make a custom scroll bar like above while matching it with the website to enhance the overall UI.

**Comment by harshit-sharmaaa** [comment]
okay start working on it
