### ISSUE TITLE
Add buttons for all pages in navbar

### ISSUE THREAD

**Issue by PranavBarthwal** [PranavBarthwal/cosmoXplore#196]
### Describe your issue

Add buttons in navbar for all pages inside the `pages` folder

### Steps to reproduce the bug

check navbar

### What was the expected result?

The navbar should have buttons for all pages

### Put here any screenshots or videos (optional)

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/110532770/f8f88700-7ed1-4a25-9865-7775cba3d4c4)

### Would you like to work on this issue?

No

### How will you fix this? (Only if you want to work on this issue)

Add buttons named `EPIC` for earthPic page
and `NeoWs` for asteroid-info page

**Comment by Anjaliavv51** [comment]
I would like to fix this issue.

**Comment by Anjaliavv51** [comment]
![image](https://github.com/PranavBarthwal/cosmoXplore/assets/154777864/fe229d6c-cec0-4725-9a83-68818a5d5e98)

**Comment by Anjaliavv51** [comment]
https://github.com/PranavBarthwal/cosmoXplore/assets/154777864/862fa388-8315-4394-b776-b792e05c2705

**Comment by Anjaliavv51** [comment]
Please review  PR #197 and merge the change if u like it!
Thank You!
