### ISSUE TITLE
Use of more professional words in the contact us section 

### ISSUE THREAD

**Issue by ayush-848** [PranavBarthwal/cosmoXplore#201]
### Describe the feature

Instead of 'We'll never share your email with anyone else', I will use 'Your email  will remain confidential and will not be shared with third parties"

In the placeholder of message The first letter is not capital. I will change it to capital

### Additional context

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/126975547/7957aa66-695c-4714-be7f-fcf3f81e5894)

### Would you like to work on this issue?
Yes

**Comment by 143divya** [comment]
Please assign this to me

**Comment by ayush-848** [comment]
@PranavBarthwal Please assign this issue to me
