### ISSUE TITLE
Bug Report: Video Rendering Issue in APOD Section of CosmoXplore Website

### ISSUE THREAD

**Issue by harithaguna** [PranavBarthwal/cosmoXplore#21]
### Describe your issue

Upon loading the APOD (Astronomy Picture of the Day) section on the CosmoXplore website, the video fails to render properly, resulting in a broken or distorted display.

### Steps to reproduce the bug

1. Visit the CosmoXplore website.
2. Navigate to the APOD section.
3. Observe the video rendering issue upon page load.

### What was the expected result?

The video in the APOD section should load correctly and display without any distortion or errors upon page load.

### Put here any screenshots or videos (optional)

![Screenshot 2024-05-10 232514](https://github.com/PranavBarthwal/cosmoXplore/assets/113124063/a49f2d27-c788-4081-a905-931a817130db)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I will investigate the cause of the video rendering issue, which may involve debugging the code and checking for compatibility with different browsers. Once identified, I'll make the necessary changes to ensure the video loads correctly upon page load.

**Comment by PranavBarthwal** [comment]
hi @harithaguna thanks for raising this issue. You can start working on this.
Additional context : currently, the APOD section is hard-coded to show image fetched from the API. But whenever we get a video from API resoonse then we get this error.

**Comment by harithaguna** [comment]
Thanks for the context. I'll start fixing it.
