### ISSUE TITLE
Home page shifting upwards

### ISSUE THREAD

**Issue by AMISH-KHAN** [PranavBarthwal/cosmoXplore#215]
### Describe your issue

The current ui has a typing effect which when erasing the text shifts upwards.
this causes a vertical shaking effect which is not visually appealing.

### Steps to reproduce the bug

1: go to the page
2: wait for some time to get the text cleared 

### Put here any screenshots or videos (optional)

https://github.com/PranavBarthwal/cosmoXplore/assets/123164129/e88bec8e-cff7-401e-957a-d708c684c793

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I can wrap the text which has typing effect inside a div and will give that div a fixed height

**Comment by AMISH-KHAN** [comment]
@PranavBarthwal please assign this issue to me!!

**Comment by PranavBarthwal** [comment]
this issue is already fixed.
