### ISSUE TITLE
<ISSUE> Update Homepage Main Heading Styling

### ISSUE THREAD

**Issue by jollyhub8278** [PranavBarthwal/cosmoXplore#217]
### Describe your issue

Home page of the website consists the main heading "Let's embark on a Cosmic X.......". I have noticed an issue that after the removal of complete spelling of X...... the space between heading and its paragraph will be gone and its not looking good at all. I want to make it clear and enhance the overall look of website.

### Steps to reproduce the bug

1. Open the Website
2. click on Home page

### What was the expected result?

The position of "X" must be fixed only the spelling after "X" must be replaced not the complete spelling.

### Put here any screenshots or videos (optional)

![Screenshot 2024-05-21 113046](https://github.com/PranavBarthwal/cosmoXplore/assets/142597742/06778a1d-c1f1-4a1a-b69d-a527b775dcca)
![Screenshot 2024-05-21 112558](https://github.com/PranavBarthwal/cosmoXplore/assets/142597742/48e5e1a6-f876-4e17-b669-0da4923cb47c)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I'll fix it by making X fix at the same place.

**Comment by PranavBarthwal** [comment]
This issue was already assigned to someone else. Please check other issues before creating your own to avoid duplicates.
