### ISSUE TITLE
Typos in source code

### ISSUE THREAD

**Issue by Chandu6702** [PranavBarthwal/cosmoXplore#226]
### Describe your issue

There are a few typos in the source code and issues template which take a lot of time to find and resolve, and it doesn't follow the proper naming convention.

### Steps to reproduce the bug

1. Go to line number 9 DisplayDetails.jsx.
2. Go to line number 16 in doc_report.yml
3. we can find the typos there.

### Put here any screenshots or videos (optional)

![Screenshot 2024-05-22 192515](https://github.com/PranavBarthwal/cosmoXplore/assets/125206920/5b7b280e-bb05-4784-858c-b7dcc5f1ae38)
![Screenshot 2024-05-22 192544](https://github.com/PranavBarthwal/cosmoXplore/assets/125206920/00796d9a-455f-4b0d-bef1-7a23bfbd2677)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I can review all the source code and documentation to find and resolve typos.

**Comment by Chandu6702** [comment]
@surajvast1 please assign this to me

**Comment by surajvast1** [comment]
Go on @Chandu6702 .If you find any any files that is not necessary update in the .gitignore

**Comment by Chandu6702** [comment]
@surajvast1 Okay, thankyou, and also please check the other issues I raised.
