### ISSUE TITLE
Calendar has red background

### ISSUE THREAD

**Issue by DonaldReddy** [PranavBarthwal/cosmoXplore#227]
### Describe your issue

Calendar input has a red background.

https://github.com/PranavBarthwal/cosmoXplore/assets/83972294/99012e81-5496-4417-b75f-bb2d6b450ce8

### Steps to reproduce the bug

1. Go to the home page.
2. scroll down to the Mars rover section.
3.  Behind the calendar input we can see a red background.

### Put here any screenshots or videos (optional)

https://github.com/PranavBarthwal/cosmoXplore/assets/83972294/b9811b36-79e2-4223-931c-a3c05fcf5d17

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I fix this by removing the background color.

**Comment by Ketanop321** [comment]
sir @DonaldReddy  assign this issue to me , i can solve this issue in an hour🤗
