### ISSUE TITLE
Floating Animation On Images

### ISSUE THREAD

**Issue by Chandu6702** [PranavBarthwal/cosmoXplore#228]
### Describe the feature

 the images in hero section ,mars rover section and contact section will float. 

### It should be implemented because

At present only box-shadow is appearing on hovering,by adding the floating animation it matches the theme of the project "cosmoXplore" .

### Additional context

please assign this to me.

### Would you like to work on this issue?

Yes

**Comment by PranavBarthwal** [comment]
go ahead
