### ISSUE TITLE
Enhancement in home page

### ISSUE THREAD

**Issue by Chandu6702** [PranavBarthwal/cosmoXplore#229]
### Describe the feature

for Sections no proper margin and gap. it affects user experience.
Everything very near to eachother.
I will enhance the home page.

### Additional context
![Screenshot 2024-05-23 122641](https://github.com/PranavBarthwal/cosmoXplore/assets/125206920/fbe504b4-684a-4dbe-8794-839f0d017e6f)

![Screenshot 2024-05-23 122700](https://github.com/PranavBarthwal/cosmoXplore/assets/125206920/bc5d3821-e8ab-4180-a748-c75fe014fe53)

![Screenshot 2024-05-23 122720](https://github.com/PranavBarthwal/cosmoXplore/assets/125206920/91c857d8-cdc3-4865-b6a6-6cedfc34c102)

Please assign this to me

### Would you like to work on this issue?

Yes

**Comment by harshit-sharmaaa** [comment]
use proper format with screenshots

**Comment by Chandu6702** [comment]
@harshit-sharmaaa please check now

**Comment by Ketanop321** [comment]
It is really necessary to give enough padding and margin between elements. I can fix this issue for you @Chandu6702 , kindly assign this issue to me

**Comment by harshit-sharmaaa** [comment]
start working @Chandu6702
