### ISSUE TITLE
[Feature]: New Separate Page for Astronomy Picture of The Day

### ISSUE THREAD

**Issue by Vaibhavsg17** [PranavBarthwal/cosmoXplore#23]
### Describe the feature

This feature involves creating a dedicated page within the application for displaying the Astronomy Picture of The Day (APOTD). The page will showcase stunning astronomical images along with accompanying descriptions, providing users with a daily dose of awe-inspiring content related to space and astronomy.

### It should be implemented because

1. Educational Value: Providing users with access to APOTD content offers a valuable educational opportunity, allowing them to learn about various celestial phenomena, space missions, and astronomical discoveries.
2. Engagement: A dedicated APOTD page will enhance user engagement by offering captivating and informative content that appeals to individuals interested in astronomy and space exploration.
3. Interest Diversification: Integrating APOTD content diversifies the application's content offerings, catering to the interests of users who have a passion for astronomy and related topics.
4. Community Building: The APOTD page can serve as a focal point for discussions and interactions among users who share a common interest in astronomy, fostering a sense of community within the application.
5. Enhanced User Experience: By curating high-quality astronomical images and informative descriptions, the APOTD page enriches the user experience and adds value to the application.

### Additional context

The addition of a separate page for Astronomy Picture of The Day enhances the application's content offerings and provides users with a unique and enriching experience. By incorporating APOTD content, the application can attract and retain users interested in astronomy, while also promoting curiosity, learning, and discovery.

### Would you like to work on this issue?

Yes

**Comment by Vaibhavsg17** [comment]
@pawas108ram assign this to me

**Comment by PranavBarthwal** [comment]
@Vaibhavsg17 I don't feel the need of a new for APOD, you can find another issue.
Thanks.
