### ISSUE TITLE
contact form is submitted without filling the fields

### ISSUE THREAD

**Issue by Chandu6702** [PranavBarthwal/cosmoXplore#237]
### Describe your issue

When we submit the form without filling in the data it is accepted.

### Steps to reproduce the bug

1. Go to the contact section
2. click submit without filling

### Put here any screenshots or videos (optional)

https://github.com/PranavBarthwal/cosmoXplore/assets/125206920/891aad6f-0c80-4d3b-b840-c19e5f90bcf6

### Would you like to work on this issue?

Yes

**Comment by Chandu6702** [comment]
@surajvast1 please assign this to me

**Comment by surajvast1** [comment]
Can you also work on the disign part of it to match the theme and  implement email js free service here . 
You will be assigned this only after confirmation

**Comment by Chandu6702** [comment]
Okay I'll work on this

**Comment by Chandu6702** [comment]
@surajvast1 Thank you and please look into my other issues to.

**Comment by surajvast1** [comment]
Add this mail id : 
pbarthwal90@gmail.com
