### ISSUE TITLE
Issue with input date in mars illustration section

### ISSUE THREAD

**Issue by Chandu6702** [PranavBarthwal/cosmoXplore#238]
### Describe your issue

On clicking the enter button the mars rover illustration is displayed without entering the date.

### Steps to reproduce the bug

1. Go to Mars rover input field
2.  click enter

### Put here any screenshots or videos (optional)

https://github.com/PranavBarthwal/cosmoXplore/assets/125206920/1ecbd4af-28fd-4b2b-ac36-85c6daa952bf

### Would you like to work on this issue?

Yes

**Comment by Chandu6702** [comment]
@surajvast1 please assign this to me

**Comment by surajvast1** [comment]
Are you taking about this 
![image](https://github.com/PranavBarthwal/cosmoXplore/assets/99933579/89fe83ae-84af-4f66-bba1-a01343aee2bd)

**Comment by surajvast1** [comment]
Go on @Chandu6702

**Comment by Chandu6702** [comment]
Thank you @surajvast1 , I'll start working on this issue as soon as the project structure is updated #230  to avoid the merge conflicts.
Is it okay.

**Comment by surajvast1** [comment]
Yeahh sureee
