### ISSUE TITLE
Favicon icon missing

### ISSUE THREAD

**Issue by karthickkumarsm** [PranavBarthwal/cosmoXplore#240]
### Describe your issue

favicon is missing in website

### Steps to reproduce the bug

just open the website and check

### Put here any screenshots or videos (optional)

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/89688112/6a44e706-cb49-4d2f-83d9-5f66da375526)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

i fix this by adding an favicon icon

**Comment by surajvast1** [comment]
Go on Add it then

**Comment by karthickkumarsm** [comment]
@surajvast1 pr created.Kindly review it
