### ISSUE TITLE
Make the navbar sticky

### ISSUE THREAD

**Issue by Madhuri36** [PranavBarthwal/cosmoXplore#251]
### Describe the feature

This feature enhances user experience by making the navigation bar 'sticky', ensuring it remains fixed at the top of the screen as users scroll through the page.

### It should be implemented because

Users can easily access important navigation links and menus without having to scroll back to the top of the page.

### Additional context

I would like to work on this. @PranavBarthwal @harshit-sharmaaa please assign this to me under GSSoC'24.

### Would you like to work on this issue?

Yes

**Comment by nishitasinghhh** [comment]
@PranavBarthwal  Kindly assign this issue to me

**Comment by PranavBarthwal** [comment]
its already fixed
