### ISSUE TITLE
Adding social media icons in footer 

### ISSUE THREAD

**Issue by suhanigupta23** [PranavBarthwal/cosmoXplore#253]
### Describe the feature

We can add social media icons in the footer section.

### Additional context

<img width="1431" alt="Screenshot 2024-05-25 at 8 32 38 AM" src="https://github.com/PranavBarthwal/cosmoXplore/assets/144280247/300ce76f-2fe3-4b5c-aa68-0fd91e0c1ba8">
I would like to work on this issue under Gssoc'24.

### Would you like to work on this issue?

Yes

**Comment by Prachi309** [comment]
@suhanigupta23 please assign this issue to me!

**Comment by Prachi309** [comment]
@PranavBarthwal please assign this issue to me

**Comment by PranavBarthwal** [comment]
Thanks for raising this issue but I like the Footer to be minimal and not have any social media links
