### ISSUE TITLE
Enhance Usability: Replace Text Inputs with Date Pickers

### ISSUE THREAD

**Issue by piyush-gambhir** [PranavBarthwal/cosmoXplore#26]
### Describe the feature

Currently, users are required to manually type dates into text input fields. This can be prone to errors and inconsistencies in formatting (e.g., "05/11/2024" vs. "11-05-2024"). To improve the user experience and data accuracy, we should integrate date picker components for all date-related inputs.

### It should be implemented because

By integrating date pickers, we anticipate several benefits. First, date pickers are more intuitive and easier to use than manually typing dates, leading to a smoother user experience. Second, they will significantly reduce errors by eliminating typos and enforcing a standardized date format (e.g., YYYY-MM-DD). This standardization will ensure data consistency across our application.

### Additional context

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/90608533/e6706b87-1dab-4099-8aeb-7a5f66130840)

### Would you like to work on this issue?

Yes

**Comment by PranavBarthwal** [comment]
@piyush-gambhir this is a duplicate issue. This is already adressed in #19.
You may find some other issue.
Thanks
