### ISSUE TITLE
Would like to add reveL elements on scroll and parallax custom cursor?

### ISSUE THREAD

**Issue by Anjaliavv51** [PranavBarthwal/cosmoXplore#260]
### Describe the feature

https://youtu.be/Zwa5z9Ws7y4?si=3NNZz-gNmc7zp72R

https://youtu.be/kmM6mqvnxcs?si=P3XQRJNxcNaiKc4p

Ever wondered how websites smoothly reveal content as you scroll? 
Do u also want to ur website❓

### It should be implemented because

It looks great when elements reveal on scroll

### Additional context

Please assign this issue to me...
Please assign this repo under GSSOC 24....
Thank You...

### Would you like to work on this issue?

Yes

**Comment by PranavBarthwal** [comment]
Go ahead

**Comment by Anjaliavv51** [comment]
@PranavBarthwal please review the changes

**Comment by Anjaliavv51** [comment]
@DonaldReddy i will solve that

**Comment by Anjaliavv51** [comment]
![image](https://github.com/PranavBarthwal/cosmoXplore/assets/154777864/e3aa7fcd-ff7b-4b17-b753-521248b8c392)


![image](https://github.com/PranavBarthwal/cosmoXplore/assets/154777864/54e79faf-e7e4-43d0-8eac-93f0fb544c0b)


Updated , code has no output?

**Comment by DonaldReddy** [comment]
You'll find errors in the console, and solve them.

**Comment by Anjaliavv51** [comment]
Sorry I didn't get u @DonaldReddy

**Comment by DonaldReddy** [comment]
how did you update the branch?

**Comment by Anjaliavv51** [comment]
I just deleted the old one and forked again

**Comment by DonaldReddy** [comment]
follow the steps in the readme file.

**Comment by Anjaliavv51** [comment]
@PranavBarthwal I will make , the changes according to react , it takes some time for me

**Comment by PranavBarthwal** [comment]
> @PranavBarthwal I will make , the changes according to react , it takes some time for me

No worries, take your time.

**Comment by PranavBarthwal** [comment]
> I just deleted the old one and forked again 
Instead of doing this learn how to sync the fork and pull the changes in your local system.

**Comment by Anjaliavv51** [comment]
@PranavBarthwal please review the changes.
