### ISSUE TITLE
An About Page to Show Founder and Contributors.

### ISSUE THREAD

**Issue by DonaldReddy** [PranavBarthwal/cosmoXplore#262]
### Describe the feature

A page dedicated to showing founders and contributors. and about the project.

We can use GitHub API to fetch the details of contributors.

### Would you like to work on this issue?

Yes

**Comment by DonaldReddy** [comment]
@PranavBarthwal assign this issue

**Comment by PranavBarthwal** [comment]
Go ahead.

**Comment by harshcodesit** [comment]
hey @PranavBarthwal ,
My name is Harshwardhan Singh Panwar and I'm a contributor at GSSOC'24 .

idea:- By incorporating div CSS and animations, I can design the About us page in an interactive manner, making it visually appealing.

Please assign this task to me, GSSOC'24 .

**Comment by PranavBarthwal** [comment]
> hey @PranavBarthwal , My name is Harshwardhan Singh Panwar and I'm a contributor at GSSOC'24 .
> 
> idea:- By incorporating div CSS and animations, I can design the About us page in an interactive manner, making it visually appealing.
> 
> Please assign this task to me, GSSOC'24 .

already assigned to @DonaldReddy 
you can create new issues. 
Thanks

**Comment by surajvast1** [comment]
Hey @DonaldReddy Update??

**Comment by DonaldReddy** [comment]
@surajvast1 It will be done by tomorrow.
