### ISSUE TITLE
make APOD title and its image inline

### ISSUE THREAD

**Issue by Ketanop321** [PranavBarthwal/cosmoXplore#266]
### Describe your issue

APOD title and its image which is below of it , it would look better if it is same aligned in horizontal line.

### Steps to reproduce the bug

1.go to page 
2.scroll down to Astronomy Picture of The Day, you will se the image is below of the text

### What was the expected result?

It would look better aligned in horizontal with the text, i had pasted an image of how should it look like ⤵️

![Screenshot 2024-05-27 204216](https://github.com/PranavBarthwal/cosmoXplore/assets/146806880/f6a7335b-47b0-4525-b435-c29d9ec70043)

### Put here any screenshots or videos (optional)

![Screenshot 2024-05-27 204942](https://github.com/PranavBarthwal/cosmoXplore/assets/146806880/1aac9f17-9b8f-45d8-8686-133b70bde2e4)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I will fix it just by using flex box or any other properties that are used it

**Comment by PranavBarthwal** [comment]
its already fixed
