### ISSUE TITLE
Implementation of APoD with NASA api key

### ISSUE THREAD

**Issue by saketh-05** [PranavBarthwal/cosmoXplore#267]
### Describe the feature

The APoD section in the website is static, I want to make it dynamic with the help of NASA's api key. I will make it fully functional with day to day response updation. I will implement api response with the existing UI of the website.
It will date as a parameter to generate APoD of the specific date. APoD can be an image or video and I will try to work to implement for both cases.

### It should be implemented because

It is improve website look and feel. It will be a very good new appearance to the website.

### Additional context

![Screenshot 2024-05-27 205744](https://github.com/PranavBarthwal/cosmoXplore/assets/134281589/8f843b3e-7737-40ee-9cdf-e77315aa7b9f)
![Screenshot 2024-05-27 205838](https://github.com/PranavBarthwal/cosmoXplore/assets/134281589/da717f07-3251-40a8-b6b8-1b7f3aa300af)

### Would you like to work on this issue?

Yes

**Comment by DonaldReddy** [comment]
@saketh-05 This section is dynamic, it changes every day if it can find the APoD for that day, else a default image will be shown. 

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/83972294/0ebc86eb-c6e7-4b0e-b039-9b533a399005)

**Comment by PranavBarthwal** [comment]
> ### Describe the feature
> The APoD section in the website is static, I want to make it dynamic with the help of NASA's api key. I will make it fully functional with day to day response updation. I will implement api response with the existing UI of the website. It will date as a parameter to generate APoD of the specific date. APoD can be an image or video and I will try to work to implement for both cases.
> 
> ### It should be implemented because
> It is improve website look and feel. It will be a very good new appearance to the website.
> 
> ### Additional context
> ![Screenshot 2024-05-27 205744](https://private-user-images.githubusercontent.com/134281589/334152191-8f843b3e-7737-40ee-9cdf-e77315aa7b9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzU3MTksIm5iZiI6MTcxNjgzNTQxOSwicGF0aCI6Ii8xMzQyODE1ODkvMzM0MTUyMTkxLThmODQzYjNlLTc3MzctNDBlZS05Y2RmLWU3NzMxNWFhN2I5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxODQzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjNhMmJmNDkwNTJjNzk3ZTE5ODk1YjBmMTYxNWQ3MzhlMjc1ZWQyZmI3ZGNkMjE4ZTk0ZjM3NTFjMTQxZjcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j8RE0HTOjV5yE92X1kH814P57u_2VG9QSnNpZuSJjkE) ![Screenshot 2024-05-27 205838](https://private-user-images.githubusercontent.com/134281589/334152437-da717f07-3251-40a8-b6b8-1b7f3aa300af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MzU3MTksIm5iZiI6MTcxNjgzNTQxOSwicGF0aCI6Ii8xMzQyODE1ODkvMzM0MTUyNDM3LWRhNzE3ZjA3LTMyNTEtNDBhOC1iNmI4LTFiN2YzYWEzMDBhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxODQzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDE3Y2VlMmVkMDY4YWIxOGI1NTIwMmVmY2U4Y2M1MzExNjYxYWM3ZTAyOGFlZDczYWNlZDRhMmNiYThiYjI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7AA47r2S_3yNHzAExGpSBmlRPLbswFHKNgRyDGnXGUs)
> 
> ### Would you like to work on this issue?
> Yes


It is already implemented, you can check at https://cosmo-xplore.vercel.app/
