### ISSUE TITLE
Enhance the UI of footer

### ISSUE THREAD

**Issue by Saimanjari777** [PranavBarthwal/cosmoXplore#268]
### Describe your issue

The footer section seems incomplete.
I would like to work on this issue.
Please assign this task to me @pr

### Steps to reproduce the bug

1. In the homepage 
2.  footer section

### What was the expected result?

Enhanced UI of footer

### Put here any screenshots or videos (optional)

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/130165687/da24158b-04fa-44ff-8fe0-2a8d9cd430cb)
Enhance this footer

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I would like to add
1. Description about website
2. social media icons
3. subscription button

**Comment by PranavBarthwal** [comment]
Thanks for raising this issue but I like the Footer to be minimal and not have any social media links
