### ISSUE TITLE
Add Code of Conduct file

### ISSUE THREAD

**Issue by suhanipaliwal** [PranavBarthwal/cosmoXplore#27]
Currently, the repository lacks a Code of Conduct file, which is an essential component for fostering a healthy and inclusive open-source community. A Code of Conduct serves as a guideline for expected behaviour, ensuring that contributors and participants feel safe, respected, and valued within our community space.

Please assign this issue to me.

**Comment by PranavBarthwal** [comment]
@suhanipaliwal go ahead, assigned!

**Comment by PranavBarthwal** [comment]
@suhanipaliwal Please follow [these](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project#adding-a-code-of-conduct-using-a-template) instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md
