### ISSUE TITLE
Add Particles background

### ISSUE THREAD

**Issue by PranavBarthwal** [PranavBarthwal/cosmoXplore#270]
### Describe the feature

add a particle background.

Inspiration : https://www.namespacecomm.in/
https://github.com/namespacecomm/NSCC-BPIT-Website

### Would you like to work on this issue?

None

**Comment by PranavBarthwal** [comment]
> @PranavBarthwal Please assign this issue to me.

Also, please remove all the irrelavant files of the previous particle BG.

**Comment by DonaldReddy** [comment]
Sure @PranavBarthwal
