### ISSUE TITLE
Issue with Navigation to Home Sections from Different Route

### ISSUE THREAD

**Issue by Uday2902** [PranavBarthwal/cosmoXplore#271]
### Describe your issue

When navigating to "NASA's Projects" (route: /nasa-projects) and clicking on "APoD" or "Martian Imagery," the application does not correctly navigate to the corresponding sections (/#apod or /#mars) on the homepage. Instead, it appends the hash routes to the current URL, resulting in invalid routes such as /nasa-projects/#apod and /nasa-projects/#mars.

### Steps to reproduce the bug

1. Go to page NASA's Projects
2. Click on MartianImagery or APoD

### What was the expected result?

Clicking on "APoD" or "Martian Imagery" while on the /nasa-projects route, should navigate the user to /#apod and /#mars respectively, effectively taking the user back to the homepage and scrolling to the appropriate sections.

### Put here any screenshots or videos (optional)

Current behaviour : 

https://github.com/PranavBarthwal/cosmoXplore/assets/127274394/da52b4c5-1aed-4bf2-84de-99e8d19ec096

Expected behaviour : 

https://github.com/PranavBarthwal/cosmoXplore/assets/127274394/84d84e33-fe0f-4082-943f-2bd4efe78e4e

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

To fix the issue of navigating to specific sections on the home page, I used the useNavigate and useLocation hooks and added a useEffect to handle the scroll behavior. This ensures that clicking on links like APOD or MartianImagery correctly navigates to /#apod or /#mars without appending them to the current path, and handles smooth scrolling to those sections or to the top of the page for the home link.

I would like to work on this issue under GSSOC'24. I request you to assign this issue to me.

**Comment by PranavBarthwal** [comment]
assigned
