### ISSUE TITLE
Photo is missing

### ISSUE THREAD

**Issue by Shreyaa173** [PranavBarthwal/cosmoXplore#274]
### Describe your issue

The photo on Astronomy Picture of The Day is missing.

### Steps to reproduce the bug

By addingthe picture

### Put here any screenshots or videos (optional)

![Screenshot 2024-05-28 111837](https://github.com/PranavBarthwal/cosmoXplore/assets/144673309/093fcc8a-5392-4152-8a78-e16081392c86)

### Would you like to work on this issue?

Yes

**Comment by AMS003010** [comment]
The bug can be resolved by using the api endpoint correctly. I looked into it and the api endpoint for APOD is working properly.  Please do would assign me this issue. I wanted to work on it under gssoc 24

**Comment by DonaldReddy** [comment]
This issue is covered in open PR.
