### ISSUE TITLE
Making navbar responsive for all devices

### ISSUE THREAD

**Issue by saketh-05** [PranavBarthwal/cosmoXplore#276]
### Describe the feature

The navbar in the website doesn't look good as the hamburger icon is placed wrong and the links of navbar are oddly arranged which degrade the appearance of website from mobile or tab.

### It should be implemented because

Bad response

### Additional context

![Screenshot 2024-05-28 131745](https://github.com/PranavBarthwal/cosmoXplore/assets/134281589/decbd01b-8f86-497e-970c-205e5386de14)
![Screenshot 2024-05-28 131803](https://github.com/PranavBarthwal/cosmoXplore/assets/134281589/a12b431a-3988-4c15-be35-e16e0eb02fb3)

### Would you like to work on this issue?

Yes

**Comment by PranavBarthwal** [comment]
go ahead

**Comment by lovelymahor** [comment]
Please assign it to me I want to work on this
