### ISSUE TITLE
Favicon.ico is not showing in the website header

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [PranavBarthwal/cosmoXplore#278]
### Describe your issue

Favicon.ico is not showing in the website header

### Steps to reproduce the bug

Favicon.ico is not showing in the website header

### Put here any screenshots or videos (optional)

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/125277258/f0b3413f-9dfc-4a64-a293-90669ab45086)

### Would you like to work on this issue?

Yes

**Comment by RamakrushnaBiswal** [comment]
gssoc 24

**Comment by Tanishka023** [comment]
Heyy !! @PranavBarthwal I am excited to contribute to this project; please assign it to me under GSSOC'24.
