### ISSUE TITLE
Explore button is not looks good.

### ISSUE THREAD

**Issue by zalabhavy** [PranavBarthwal/cosmoXplore#279]
### Describe the feature

Explore button's color should be purple or dark blue it will more attractive also some extra hover effects will make it perfect.

### It should be implemented because

It is important for better user experince.

### Additional context

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/126322584/6848a259-57e1-4aec-a062-f230aa174e99)
This is looks normal i will give it style.

### Would you like to work on this issue?

Yes

**Comment by harshcodesit** [comment]
@zalabhavy 
I want to work on the issue to make the button more immersive 

please assign me
