### ISSUE TITLE
Project page is croped and not proper for Mobile screen

### ISSUE THREAD

**Issue by Utsavladia** [PranavBarthwal/cosmoXplore#280]
### Describe your issue

The Nasa Projects page is not properly responsive for the Mobile screen and the user is unable to read it properly.

It should be improved to make it responsive

### Steps to reproduce the bug

Go to NASA projects section and turn Mobile view from inspect.

### What was the expected result?

It should be visible properly in the Mobile scrren also

### Put here any screenshots or videos (optional)

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/124615886/96c3b444-2cb6-4a3b-b45e-1430a6ee8f6a)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I will change the styling of it to make to look good on mobile screen and give a better user experience.

**Comment by PranavBarthwal** [comment]
go ahead
