### ISSUE TITLE
All routes are not handled in vercel and give 404 NOT FOUND on refresh

### ISSUE THREAD

**Issue by Utsavladia** [PranavBarthwal/cosmoXplore#281]
### Describe your issue

When we refresh on any page it gives ERROR 404 NOT FOUND

### Steps to reproduce the bug

go to any section other than Home and refresh the page

### What was the expected result?

It should either redirect to Home page or Stay on that page if available on Refreshing the page

### Put here any screenshots or videos (optional)

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/124615886/19804d02-e0c0-4674-9d7e-517cd5d357ed)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I will add the Vercel configuration file to handle the routing of all pages properly and redirect properly.

**Comment by PranavBarthwal** [comment]
go ahead
