### ISSUE TITLE
Navigation got Stuck and dont work for Mobile screen 

### ISSUE THREAD

**Issue by Utsavladia** [PranavBarthwal/cosmoXplore#282]
### Describe your issue

On click to navigate on any page in Mobile screen the Navigation bar got Black in color and No action happpend.

### Steps to reproduce the bug

Go to Mobile view and try using the Navigation.

### What was the expected result?

It shold Navigate to the desired section properly on clicking from Navbar.

### Put here any screenshots or videos (optional)

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/124615886/c8d3ebb6-4d84-48aa-a44c-1c3f83f40dcd)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I will fix this issue to properly Navigate to sections from the Navbar links and Ensure proper styling according to Mobile screen.

**Comment by PranavBarthwal** [comment]
go ahead
