### ISSUE TITLE
Need to add dynamic code for year in footer section

### ISSUE THREAD

**Issue by tarushi29** [PranavBarthwal/cosmoXplore#291]
![Screenshot 2024-05-26 235500](https://github.com/PranavBarthwal/cosmoXplore/assets/128239884/ea8b482c-7dbc-468b-b4af-e209b926c824)

Dynamic code using js function can be coded to enhance dynamic feature code for year in the footer section

**Comment by tarushi29** [comment]
@PranavBarthwal please assign me this issue under gssoc label so that i can fix it asap

**Comment by surajvast1** [comment]
Take it @tarushi29
