### ISSUE TITLE
Button to Scroll to top of page

### ISSUE THREAD

**Issue by Chandu6702** [PranavBarthwal/cosmoXplore#293]
### Describe the feature

A button that can scroll to the top of the page.
when users scroll down to the end of the page the users can go to the top by clicking this button. the 

### It should be implemented because

It enhances the user experience

### Would you like to work on this issue?

Yes

**Comment by Chandu6702** [comment]
@PranavBarthwal please assign this to me.

**Comment by surajvast1** [comment]
Go on add it @Chandu6702
