### ISSUE TITLE
Improve the interface

### ISSUE THREAD

**Issue by AkhilaSunesh** [PranavBarthwal/cosmoXplore#296]
### Describe your issue

There are no clear instructions with the calendar box.
![image](https://github.com/PranavBarthwal/cosmoXplore/assets/140897461/25de7b7b-9164-42cd-b01c-f55318455a4b)
I can add an impressive text to make it easier for the user to understand to know what the function does.
Pls assign this issue to me.

### Steps to reproduce the bug

1. Add an impressive text 

### What was the expected result?

More user friendly

### Put here any screenshots or videos (optional)

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/140897461/a1732a51-4cfb-4aaf-9e92-234f86a453e6)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

Add text which appeals to the user.

**Comment by surajvast1** [comment]
@AkhilaSunesh do you just want to work on the Ui part ??/

**Comment by surajvast1** [comment]
We want this feature to be shifted on he new page with proper Apis and good description.Removing
![image](https://github.com/PranavBarthwal/cosmoXplore/assets/99933579/f5410479-bb06-44e2-8c48-9fb48d276c4c)
Would you be willing to work on this ??

**Comment by AkhilaSunesh** [comment]
> @AkhilaSunesh do you just want to work on the Ui part ??/
> 

Yeah, otherwise the user wouldn't understand what to do

**Comment by AkhilaSunesh** [comment]
> @AkhilaSunesh  We want this feature to be shifted on he new page with proper Apis and good description.Removing
> ![image](https://github.com/PranavBarthwal/cosmoXplore/assets/99933579/f5410479-bb06-44e2-8c48-9fb48d276c4c)
> Would you be willing to work on this ??

I can give it a try.

**Comment by surajvast1** [comment]
@AkhilaSunesh A similar issue has alreasy been created and assisgned.
With all the updated features 
You can create new issues 
Thanks

**Comment by AkhilaSunesh** [comment]
Alright, Thanks for the reply
