### ISSUE TITLE
Enhancing Nav Bar

### ISSUE THREAD

**Issue by Dishika18** [PranavBarthwal/cosmoXplore#298]
### Describe the feature

Nav bar looks bit simple and have no hover effect. I would like to work on it and enhance it with a decent hover effect.
Please assign me this issue under GSSoC'24.

### Would you like to work on this issue?

Yes

**Comment by surajvast1** [comment]
Take it @Dishika18

**Comment by lovelymahor** [comment]
Please assign it to me I want to work on this

**Comment by surajvast1** [comment]
@lovelymahor, Issue already assigned .You can contribute on another issues .Keep Contributing

**Comment by surajvast1** [comment]
@Dishika18 Update??

**Comment by Dishika18** [comment]
yes i am working on it

**Comment by Dishika18** [comment]
@lovelymahor u can take this issue, ask owner to assign u!

**Comment by thecloudcode** [comment]
Kindly assign this issue to me @surajvast1 , I have worked on such issues earlier, and I would love it work on it again.

**Comment by lovelymahor** [comment]
Heyy @surajvast1 please assign it to me

**Comment by surajvast1** [comment]
@thecloudcode @lovelymahor 
 Mention the changes you wanna make to enhance the navbar .So i can assign the issue accordingly

**Comment by thecloudcode** [comment]
## After my changes
![image](https://github.com/PranavBarthwal/cosmoXplore/assets/114615639/d64467bc-1602-4802-9054-120a6df29539)

## Before
![image](https://github.com/PranavBarthwal/cosmoXplore/assets/114615639/f09b6e5b-eb91-487f-ae31-8bf73abb9164)

I have been working on your repo overnight. Tell me if you need more changes to it, so that I can send a pull request for it.

**Kindly assign me this issue, so that I can send a PR**

**Comment by surajvast1** [comment]
We appreciate your work .Go on create a pr @thecloudcode

**Comment by surajvast1** [comment]
Thank you keep contributing.

**Comment by thecloudcode** [comment]
Thanks @surajvast1 , for assigning me. I have sent a pull request, kindly review it and tell me if it needs any further improvements.

**Comment by surajvast1** [comment]
@thecloudcode Before working on any issue you must wait for the mentors to assign it to you . If the issue gets assigned to someone else or gets closed its a waste of your hardwork. Also the protocol is the person who asks for the issue gets it first .So please take care on this from now on

**Comment by thecloudcode** [comment]
@surajvast1 Sure, I will take care of it from next time, thanks 👍
