### ISSUE TITLE
Add a 404 not found page for your website

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [PranavBarthwal/cosmoXplore#301]
### Describe the feature

Add a 404 not found page for your website

### Would you like to work on this issue?

Yes

**Comment by RamakrushnaBiswal** [comment]
@PranavBarthwal @surajvast1 please assign the issue to me

**Comment by surajvast1** [comment]
Add it @RamakrushnaBiswal

**Comment by RamakrushnaBiswal** [comment]
@surajvast1 add some labels like ex- gssoc , label-2,label-3

**Comment by RamakrushnaBiswal** [comment]
Pr #316
