### ISSUE TITLE
Improving the project's Fetching time

### ISSUE THREAD

**Issue by sujal-98** [PranavBarthwal/cosmoXplore#305]
### Describe the feature

when we go to the Nasa's project page and the projects loads, the loading time is very big and can we drastically reduced if we make some changes in the code thus the projects will load a lot faster.

### It should be implemented because

The loading time for the NASA projects page is significantly high, resulting in a poor user experience thus reducing the loading time will improve the user experience on the page.

### Additional context

https://github.com/PranavBarthwal/cosmoXplore/assets/117587914/d550d556-14dc-476a-bbf8-b7e39d41bebf

### Would you like to work on this issue?

Yes

**Comment by DonaldReddy** [comment]
Hey @sujal-98 out of curiosity, how will you achieve it?

**Comment by sujal-98** [comment]
@DonaldReddy By concurrent execution of the fetch promises using map as promises are asynchronous so the code will fetch all the projects concurrently significantly reducing the time (implementing an array of promises ). To avoid hitting the rate limits, we can do this in batches like fetching the projects in batches
