### ISSUE TITLE
[Feat]: Add Preloader till BackGround Renders

### ISSUE THREAD

**Issue by DonaldReddy** [PranavBarthwal/cosmoXplore#309]
### Describe the feature

As react three fiber takes time to load the 3D Starfield.
An animated preloader is shown till it's rendered.

### It should be implemented because

It will improve user experience.

### Would you like to work on this issue?

Yes

**Comment by surajvast1** [comment]
This is needed. See to it that it maches the website's theme 
Take it @DonaldReddy
