### ISSUE TITLE
Adding Space animation

### ISSUE THREAD

**Issue by harshmishra19** [PranavBarthwal/cosmoXplore#311]
### Describe the feature

Adding this animation with the current theme 

### It should be implemented because

To make the website look more appealing

### Additional context

https://github.com/PranavBarthwal/cosmoXplore/assets/115486960/581920b9-a068-4d04-9864-5f18f2913fc6

### Would you like to work on this issue?

None

**Comment by surajvast1** [comment]
Apologies particle js is not needed.
