### ISSUE TITLE
In Nasa product page if i want to navigate into apod page it doesno't works

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [PranavBarthwal/cosmoXplore#313]
### Describe your issue

In Nasa product page if i want to navigate into apod page it doesno't works

### Steps to reproduce the bug

1-go to NASA-project page
2-then click the apod link in the navbar
3-you can't navigate

### What was the expected result?

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/125277258/04c242ae-ae83-4cd0-960b-e9ffad483821)
The URL doesn't exist in the page,

### Put here any screenshots or videos (optional)

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/125277258/aff301f5-4fd9-4d65-b5f5-0629301a8596)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

it need to be Routing issue

**Comment by surajvast1** [comment]
Good issue @RamakrushnaBiswal

**Comment by surajvast1** [comment]
Take it

**Comment by DonaldReddy** [comment]
#315

**Comment by surajvast1** [comment]
Already Taken

**Comment by surajvast1** [comment]
You can work on other issues @RamakrushnaBiswal
