### ISSUE TITLE
[Doc]: Improving main Readme/md file

### ISSUE THREAD

**Issue by Anjaliavv51** [PranavBarthwal/cosmoXplore#317]
### Describe the bug

- [X] Information addition regarding the newest change through a PR.
- [X] Typo error.
- [X] New category addition.
- [X] Refractoring sentences that make more sense.
- [X] Fixing broken links.
- [X] Refractors / reformatting of the document.

### Additional Context

Adding contributor's list logo's and add tech stack of this repo and adding no of forks , stars and views etcc.....

**Comment by PranavBarthwal** [comment]
@Anjaliavv51 add screenshots of the website as well

**Comment by Anjaliavv51** [comment]
@PranavBarthwal please review the readme.md file
