### ISSUE TITLE
Fixed Position of back to top option

### ISSUE THREAD

**Issue by paulkrishanu4** [PranavBarthwal/cosmoXplore#330]
### Describe your issue

Back to top button is fixed in position, it should be displayed only when we move down the screen.

### Steps to reproduce the bug

specifying a condition to window scroll and change the visibility of back to top button

### Put here any screenshots or videos (optional)

https://github.com/PranavBarthwal/cosmoXplore/assets/169196836/82f0e66d-47a9-47b1-b915-a090dc3e8d30

### Would you like to work on this issue?

Yes

**Comment by harshit-sharmaaa** [comment]
start working on it
