### ISSUE TITLE
[Bug]: Navbar Hamburger doesn't work properly

### ISSUE THREAD

**Issue by shreyash3087** [PranavBarthwal/cosmoXplore#335]
### Describe your issue

The Navbar has a hamburger menu for smaller devices that doesnt work properly, the styling is not proper,also if the user toggles the hamburger menu and makes the screen bigger the hamburger menu doesnt disappear.
(Also the codebase for navbar contains a few minor issues,contains a couple of spelling errors like navabar.css)

### Steps to reproduce the bug

- Open the webpage on a small device or resize the browser window to a smaller width.
- Click on the hamburger menu in the navbar(which is not properly alligned).
- Observe the styling errors in the menu.
- Without closing the hamburger menu,make the window size larger,observe the hamburger menu doesnt toggle off.

### What was the expected result?

The Hamburger menu should have closed automatically if the screen width was increased to a certain point.

### Put here any screenshots or videos (optional)

![Screenshot (181)](https://github.com/PranavBarthwal/cosmoXplore/assets/72603662/0b41aaf3-4c34-4886-8687-e12818fb851a)
![Screenshot (183)](https://github.com/PranavBarthwal/cosmoXplore/assets/72603662/0a8fb785-84a0-459f-b0ed-75cb89075d2e)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

Made a new navbar with a hamburger menu that fits with the current theme and fixes all the current issues.

https://github.com/PranavBarthwal/cosmoXplore/assets/72603662/247cbbd7-131b-41bb-8210-e456700f233a

**Comment by surajvast1** [comment]
Hey @shreyash3087 there are this bugs in the mobile view , would you take this full issue to refactor code to be compactible for all devices . if yes I can aasign you this under level3 gssoc.(Only if you are confident or we can just move on with this )

**Comment by shreyash3087** [comment]
@surajvast1 yeah i noticed that,but no problem i can fix that,i'll make sure that the website is compatible for all the devices,you can assign me the issue.

**Comment by surajvast1** [comment]
Thanks @shreyash3087
