### ISSUE TITLE
[Doc]: Update contributing.md for github Desktop

### ISSUE THREAD

**Issue by Maheshwari-Love** [PranavBarthwal/cosmoXplore#336]
### Describe the bug

- [X] Information addition regarding the newest change through a PR.
- [ ] Typo error.
- [ ] New category addition.
- [ ] Refractoring sentences that make more sense.
- [ ] Fixing broken links.
- [X] Refractors / reformatting of the document.

### Additional Context

Adding the instructions for how to contribute in this project using github desktop.

**Comment by Maheshwari-Love** [comment]
@PranavBarthwal  @surajvast1 @harshit-sharmaaa please assign me this issue...

**Comment by surajvast1** [comment]
Take it @Maheshwari-Love
