### ISSUE TITLE
Bug: Broken image in Astronomy Picture of the Day Section

### ISSUE THREAD

**Issue by SpaciousCoder78** [PranavBarthwal/cosmoXplore#34]
### Describe your issue

The image in the Astronomy Picture of the Day Section appears to be broken and doesn't display.

### Steps to reproduce the bug

1. Go to https://pranavbarthwal.github.io/cosmoXplore/
2. Scroll down to Astronomy Picture of the Day section

### Put here any screenshots or videos (optional)

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/88923986/fb463252-4aea-4a19-bca5-ec18c0e82a81)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I will make the necessary changes to the code to fix the bug

**Comment by SpaciousCoder78** [comment]
Please Assign it to me under GSSoC '24

**Comment by PranavBarthwal** [comment]
Hi @SpaciousCoder78, the broken image issue was until yesterday only due to API error, as of now it is resolved.
