### ISSUE TITLE
Redesign Mars rover imagery page 

### ISSUE THREAD

**Issue by surajvast1** [PranavBarthwal/cosmoXplore#343]
### Describe the feature

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/99933579/138247f0-1693-4646-913d-082a837c21df)
The current page looks very bland. Update page details with some interactive and informative content displayed in good looking format .You may take help from here https://science.nasa.gov/mission/mars-exploration-rovers-spirit-and-opportunity/

If we could also implement some 3d models like [04.06.2024 00_06.webm](https://github.com/PranavBarthwal/cosmoXplore/assets/99933579/f653bf8b-2229-4257-a2fb-05eb492eabd9)

This could be a good issue to learn a lot .Would anyone like to take this 

### Would you like to work on this issue?

None

**Comment by surajvast1** [comment]
This issue is open .

**Comment by DonaldReddy** [comment]
@surajvast1 I would like to work on this issue.

**Comment by DonaldReddy** [comment]
@surajvast1 please assign this issue to me
