### ISSUE TITLE
Website Main page background colour

### ISSUE THREAD

**Issue by surajvast1** [PranavBarthwal/cosmoXplore#352]
### Describe the feature

Due to someone's merge we lost our website main page background color .Get the darker version on our website back 

this->
![image](https://github.com/PranavBarthwal/cosmoXplore/assets/99933579/eeaa7885-14bc-483e-a673-778784809ef0)

to->
![image](https://github.com/PranavBarthwal/cosmoXplore/assets/99933579/1dadd1f3-7a78-4c5f-bbf0-2cc664ea52bc)

### Would you like to work on this issue?

None

**Comment by surajvast1** [comment]
you may find the link here https://cosmo-xplore.vercel.app/

**Comment by DonaldReddy** [comment]
Hey @surajvast1 please assign this issue to me.
