### ISSUE TITLE
Adding a smooth scroll effect to the website and hover effects to the navbar.

### ISSUE THREAD

**Issue by asthanegi14** [PranavBarthwal/cosmoXplore#359]
### Describe the feature

I would like to add a smooth scroll effect to improve the navigation experience. Additionally, implementing hover effects in the navbar will provide visual feedback, making it more interactive and user-friendly. These enhancements will contribute to a more polished and modern look. 

The smooth scroll effect will ensure seamless transitions between sections, while the hover effects will make the navigation more engaging.

### It should be implemented because

It will improve the navigation experience and make it more interactive and user-friendly.

### Would you like to work on this issue?

Yes

**Comment by surajvast1** [comment]
Go on @asthanegi14
