### ISSUE TITLE
Floating Animation On Images

### ISSUE THREAD

**Issue by Chandu6702** [PranavBarthwal/cosmoXplore#36]
###The feature

On Hovering on the images in hero section ,mars rover section and contact section they float.

At present only box-shadow is appearing on hovering,by adding the floating animation it matches the theme of the project "cosmoXplore" .

I am very excited to start my open source contribution journey.So,I am requesting to assign this issue to me as I am very interested to work on this.

**Comment by PranavBarthwal** [comment]
@Chandu6702 go ahead. Assigned to you.
