### ISSUE TITLE
Minor BUG:

### ISSUE THREAD

**Issue by shreya-paul-17** [PranavBarthwal/cosmoXplore#362]
### Describe your issue

Nothing much, I just want to say in the Contact Us section, in the given box it is written "feel free to...". I just want to capitalize the letter F in "FEEL".

### Steps to reproduce the bug

Go to the file and capitalize the first letter of the word "FEEL"

Current condition:
![cosmo-xplore](https://github.com/PranavBarthwal/cosmoXplore/assets/135226069/8274a47d-3176-4c7a-a91d-c6781338afd3)

### What was the expected result?

N/A

### Put here any screenshots or videos (optional)

N/A

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I would like to change as stated above by me

**Comment by surajvast1** [comment]
Take it @shreya-paul-17
