### ISSUE TITLE
Align the navigation bar in mobile view

### ISSUE THREAD

**Issue by parikhitritgithub** [PranavBarthwal/cosmoXplore#370]
### Describe your issue

Enhance the UI in mobile view by making it responsive for all devices. Align the navigation bar after clicking the hamburger icon.
please consider this under GSSOC 2024 

### Steps to reproduce the bug

1 > Open the application/website
2> right click mouse and inspect 
3> check the navbar in mobile view 

### Put here any screenshots or videos (optional)

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/124444610/c0d1811f-f33e-49d5-ab99-2af643edbb48)
![image](https://github.com/PranavBarthwal/cosmoXplore/assets/124444610/6319aae2-866f-4f1d-b10b-afbf74011f65)
![image](https://github.com/PranavBarthwal/cosmoXplore/assets/124444610/fcd59742-cb23-429d-aaae-18c948828e5a)

### Would you like to work on this issue?

Yes

**Comment by parikhitritgithub** [comment]
please assign this issue to me under GSSOC 2024

**Comment by kashi-verma** [comment]
pls assign me this issue @PranavBarthwal under GSSOC 2024.
