### ISSUE TITLE
Chatbot  UI

### ISSUE THREAD

**Issue by parikhitritgithub** [PranavBarthwal/cosmoXplore#371]
### Describe your issue

After  clicking the chatbot icon, the chatbot UI overflows the home page . please consider this issue under GSSOC 2024 

### Steps to reproduce the bug

1. go to the page 
2. click chatbot icon

### Put here any screenshots or videos (optional)

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/124444610/5f49d006-6e57-457f-ae05-a87d3f027b1c)

### Would you like to work on this issue?

Yes

**Comment by parikhitritgithub** [comment]
please assign this issue to me under GSSOC 2024

**Comment by surajvast1** [comment]
Take it @parikhitritgithub
