### ISSUE TITLE
Picture of the Day is not responsive.

### ISSUE THREAD

**Issue by nagalakshmi08** [PranavBarthwal/cosmoXplore#374]
### Describe your issue

The image in picture of the day is not visible completely in small screens.

### Steps to reproduce the bug

1.Reduce the screen size.
2.Scroll the website to see the Picture of the day section

### What was the expected result?

The image should be visible in the website completely.

### Put here any screenshots or videos (optional)

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/121669832/f704792a-97a7-4870-91b6-2f79e5db940f)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I will change the stylings of the image to ensure that it will be visible completely in the website.

**Comment by surajvast1** [comment]
Take it @nagalakshmi08
