### ISSUE TITLE
ChatBot not aligned properly for mobile devices 

### ISSUE THREAD

**Issue by saketh-05** [PranavBarthwal/cosmoXplore#378]
### Describe your issue

The chatbot feature is not responsive and it is not working for mobile devices because of improper alignment. The width and height of the screen are less than that of chatbot and the overflow of div is not looking good.

### Steps to reproduce the bug

1. Open the website in mobile or In pc, click on inspect and reduce width of the website as of mobile width.
2. Click on chatbot icon.

### What was the expected result?

Chatbot proper alignment and working for mobiles.

### Put here any screenshots or videos (optional)

![Screenshot_20240609_065447_Chrome](https://github.com/PranavBarthwal/cosmoXplore/assets/134281589/ffc2e98b-f2eb-41b8-aff0-8495aec8d95b)
![Screenshot_20240609_065603_Chrome](https://github.com/PranavBarthwal/cosmoXplore/assets/134281589/d0230b5b-5d8c-45b9-9c20-8a57b100bbfe)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I want to make chatbot feature responsive for mobile devices so that it will improve lool and feel of the website.

**Comment by surajvast1** [comment]
GO on @saketh-05
