### ISSUE TITLE
[Feat]: Enhancing Martian Imagery Page

### ISSUE THREAD

**Issue by DonaldReddy** [PranavBarthwal/cosmoXplore#379]
### Describe the feature

Improving the alignment of 3D rover models and the text.

### Additional context

@surajvast1 please assign this issue to me.

### Would you like to work on this issue?

Yes

**Comment by surajvast1** [comment]
Good job guys @PranavBarthwal and @DonaldReddy 🤘🤘

**Comment by DonaldReddy** [comment]
Thank you @surajvast1 😊
