### ISSUE TITLE
BUG 🐞: "Scroll to Top" Button and "Chat-Bot" are Overlapping

### ISSUE THREAD

**Issue by aslams2020** [PranavBarthwal/cosmoXplore#380]
### Describe your issue

Hey @PranavBarthwal, @surajvast1 & @harshit-sharmaaa,

I noticed that the "Scroll to Top" button and the WebChat bot are overlapping on the website after opening the chatbot.
This overlap affects the usability and accessibility of both features, making it difficult for users to effectively interact with the WebChat bot and the scroll button.

### Steps to reproduce the bug

1. Go to website.
2. Scroll down the page until the "Scroll to Top" button appears.
3. Observe the overlap between the "Scroll to Top" button and the WebChat bot.

### What was the expected result?

The "Scroll to Top" button and the WebChat bot should not overlap. Both elements should be easily accessible without interfering with each other. This will give a better user experience to the users using the website.

### Put here any screenshots or videos (optional)

So, Before Opening the Chatbot

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/131389695/205b31b4-97d2-4340-a639-0704499a607f)

And This is when the issue is generated after clicking on the chatbot.

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/131389695/9499f18f-6570-4056-94a5-c80ad485127d)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I would like to contribute by adjusting the positioning or z-index of the elements to ensure they do not overlap. This can be done by modifying the CSS styles for these components.

@PranavBarthwal, Could you please assign me this issue under gssoc'24 ?

**Comment by surajvast1** [comment]
Take it @aslams2020 .Only work on the alignment .please don't change anything in the boundary of the chat-box .various issue were created and already assigned . So it won't create merge conflicts later.

https://github.com/PranavBarthwal/cosmoXplore/issues/371
https://github.com/PranavBarthwal/cosmoXplore/issues/378#event-13089872735
https://github.com/PranavBarthwal/cosmoXplore/issues/376#event-13089218058

**Comment by aslams2020** [comment]
Yes @surajvast1 ..Understood, I'll focus solely on the alignment without altering the boundary of the chat-box.
Thanks for clarifying!
