### ISSUE TITLE
add 3d models 

### ISSUE THREAD

**Issue by PranavBarthwal** [PranavBarthwal/cosmoXplore#387]
### Describe the feature

add 3d models instead of statics images in every section.

### Would you like to work on this issue?

None

**Comment by DonaldReddy** [comment]
@PranavBarthwal I would like to work on this issue.

**Comment by DonaldReddy** [comment]
What kind of 3d Models would you like to have?

**Comment by PranavBarthwal** [comment]
> What kind of 3d Models would you like to have?

any space related models like planets that will go well with the theme of the website

**Comment by PranavBarthwal** [comment]
@DonaldReddy any updates?

**Comment by DonaldReddy** [comment]
@PranavBarthwal I've added 3 planets models. Please review the pr
