### ISSUE TITLE
Dropdown menu is not working properly

### ISSUE THREAD

**Issue by Ketanop321** [PranavBarthwal/cosmoXplore#389]
### Describe your issue

when i click on dropdown menu it is getting correctly

### Steps to reproduce the bug

go to page
click to dropdown elelment

### What was the expected result?

It should get open right just below the drop down button

### Put here any screenshots or videos (optional)

![Screenshot 2024-06-10 010237](https://github.com/PranavBarthwal/cosmoXplore/assets/146806880/f82f8b4f-9b60-44f3-86c5-aaf38e321392)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

fixing its js and css

**Comment by DonaldReddy** [comment]
#388

**Comment by kesharibhai84** [comment]
@Ketanop321 please assign me this issue i want to solve this

**Comment by surajvast1** [comment]
Pull your changes .This is already resolved .
Before creating a issue make sure to look whether the similar issue has been created or not .

Close this @PranavBarthwal
