### ISSUE TITLE
add favicon to the website

### ISSUE THREAD

**Issue by divyalaldinani** [PranavBarthwal/cosmoXplore#39]
### Describe the feature

 A favicon is a small image typically displayed in the browser tab next to the title of the webpage.

### It should be implemented because

it adds to Brand Recognition, user experience.

### Would you like to work on this issue?

None

**Comment by PranavBarthwal** [comment]
@divyalaldinani Thanks for raising this issue but its a duplicate issue, an is already been addressed in #18.

**Comment by PranavBarthwal** [comment]
@divyalaldinani assigned to you. Go ahead.

**Comment by divyalaldinani** [comment]
yupp, thank you
