### ISSUE TITLE
trailing cursor effect 

### ISSUE THREAD

**Issue by Chandu6702** [PranavBarthwal/cosmoXplore#390]
### Describe the feature

sample video:
https://github.com/PranavBarthwal/cosmoXplore/assets/125206920/a096c68a-eb23-4469-9f28-30361522e310
I will create a cursor effect that matches the theme of page

### Would you like to work on this issue?

Yes

**Comment by Chandu6702** [comment]
@PranavBarthwal  and @surajvast1 please assign this to me

**Comment by Chandu6702** [comment]
@PranavBarthwal and @surajvast1 please assign this to me

**Comment by surajvast1** [comment]
Go on @Chandu6702
