### ISSUE TITLE
bug in navbar

### ISSUE THREAD

**Issue by paulkrishanu4** [PranavBarthwal/cosmoXplore#393]
### Describe your issue

navbar is not working properly, desktop view of navbar disappeared.

### Steps to reproduce the bug

decode the navbar

### Put here any screenshots or videos (optional)

https://github.com/PranavBarthwal/cosmoXplore/assets/169196836/f8b45808-c8c4-49b2-87d3-a3451d68b76a

### Would you like to work on this issue?

Yes

**Comment by DonaldReddy** [comment]
#388

**Comment by surajvast1** [comment]
I have requested my team to revert changes because of which we got that error 
https://github.com/PranavBarthwal/cosmoXplore/pull/382
you can close the issue and work on some better once

**Comment by surajvast1** [comment]
Before you rush to create an issue, how about you take a moment to see if someone else has already done it? Seriously, it's not that hard.
