### ISSUE TITLE
Cross icon should align side by side of refresh icon in open bot

### ISSUE THREAD

**Issue by kapilG0** [PranavBarthwal/cosmoXplore#403]
### Describe your issue

![Screenshot_20240614_112403](https://github.com/PranavBarthwal/cosmoXplore/assets/59639410/37158b68-8024-446e-bfb0-e750bac744c4)

### Steps to reproduce the bug

Click on chat bot then in header you can see cross icon 

### Put here any screenshots or videos (optional)

![Screenshot_20240614_112403](https://github.com/PranavBarthwal/cosmoXplore/assets/59639410/5bac344e-142d-4cfd-aa8d-d45b7be4a59b)

### Would you like to work on this issue?

Yes

**Comment by kapilG0** [comment]
Hello @PranavBarthwal please assign this issue to me under gssoc 24

**Comment by surajvast1** [comment]
Go on @kapilG0

**Comment by kapilG0** [comment]
Hello @PranavBarthwal i have raised pr https://github.com/PranavBarthwal/cosmoXplore/pull/414 for this please check
