### ISSUE TITLE
Adding socials of the community in the footer section (same themed logos)

### ISSUE THREAD

**Issue by Bharath200415** [PranavBarthwal/cosmoXplore#421]
### Describe the feature

As there are non socials present in the footer section of the webpage I'd love to add new Instagram, Github and linkedin icons which would be exactly of the same theme as that of this webpage. 

### It should be implemented because

It'd help newbie users to know more about the cosmoxplore community through other social media handles.
And would increase user engagement as they would be able to follow cosmoXplore on different platforms.

### Additional context

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/91795938/95b45ce7-b7e5-4684-85d8-1b484eba9cb2)

### Would you like to work on this issue?

Yes

**Comment by Bharath200415** [comment]
@PranavBarthwal please assign me this issue, so that I can start working on this asap! and get it fixed.

**Comment by PranavBarthwal** [comment]
duplicate issue
