### ISSUE TITLE
Replace twitter with X

### ISSUE THREAD

**Issue by AkhilaSunesh** [PranavBarthwal/cosmoXplore#425]
### Describe your issue

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/140897461/62ccf557-f402-4872-aa74-2337148d127c)
Location: footer

### Steps to reproduce the bug

Use font awesome icons

### What was the expected result?

More professional outlook

### Put here any screenshots or videos (optional)

footer

### Would you like to work on this issue?

Yes

**Comment by surajvast1** [comment]
Go on @AkhilaSunesh

**Comment by solanki505** [comment]
I would like to work on this issue ,please assign me

**Comment by AkhilaSunesh** [comment]
completed @surajvast1
