### ISSUE TITLE
sphere is not fully appearing 

### ISSUE THREAD

**Issue by chaanakyaaM** [PranavBarthwal/cosmoXplore#430]
### Describe your issue

The sphere is not fully appearing according to the website resposiveness.

### Steps to reproduce the bug

1. Go to Home page
2. resize the window to its half.

### What was the expected result?

The sphere should appear fully.

### Put here any screenshots or videos (optional)

![Screenshot (270)](https://github.com/PranavBarthwal/cosmoXplore/assets/131477601/0d360620-f434-4a92-8e09-7e3db8092ba7)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I would like to scale down the sphere to 0.9 or 0.8 according , because the div which is containing the sphere has 100% width.

**Comment by chaanakyaaM** [comment]
would you assign it to me?

**Comment by PranavBarthwal** [comment]
go ahead
