### ISSUE TITLE
MultiLanguage Facility

### ISSUE THREAD

**Issue by Ojas-Arora** [PranavBarthwal/cosmoXplore#443]
### Describe the feature

@PranavBarthwal I want to add multiple language facility to the website.Kindly assign this issue to me.

### It should be implemented because

It allows multiple languages in website.

### Additional context

NA

### Would you like to work on this issue?

Yes

**Comment by surajvast1** [comment]
Sure take it @Ojas-Arora

**Comment by Ojas-Arora** [comment]
@surajvast1 Can u also look at my previous pr please
