### ISSUE TITLE
Adding Animation 

### ISSUE THREAD

**Issue by harshmishra19** [PranavBarthwal/cosmoXplore#45]
### Describe the feature

An animation on the image of your landing page which will keep on moving and will make you page look more Appealing 

### Additional context

Could you plz assign this issue to me under GSSOC'24

### Would you like to work on this issue?

Yes

**Comment by PranavBarthwal** [comment]
@harshmishra19 go ahead

**Comment by Paavni-Goyal** [comment]
Hey, I would like to work on the same. Can you please assign this to me under GSSoC'24.
