### ISSUE TITLE
Enable transition effects when hovering over navbar sections.

### ISSUE THREAD

**Issue by arifakhtar51** [PranavBarthwal/cosmoXplore#46]
### Describe the feature

Enable transition effects when hovering over navbar sections on the Home page featuring APoD Martian Imagery.

### It should be implemented because

introduce a captivating transition effect to enhance user experience when navigating through navbar sections on the Home page..

### Additional context

![Screenshot 2024-05-11 142049](https://github.com/PranavBarthwal/cosmoXplore/assets/120799230/05a698ae-70e3-46d2-8e5f-9899c938a143)

### Would you like to work on this issue?

Yes

**Comment by PranavBarthwal** [comment]
go ahead @arifakhtar51

**Comment by Danish0703** [comment]
please assign this task to me
