### ISSUE TITLE
Close dropdown auto on choosing any option

### ISSUE THREAD

**Issue by Utsavladia** [PranavBarthwal/cosmoXplore#467]
### Describe your issue

![image](https://github.com/user-attachments/assets/5b55a35f-a6ed-441f-a3f0-7a1e727c6970)

on choosing any option it should be closed

### Steps to reproduce the bug

Go to the mobile view
open dropdown
choose any link 
dropdown will stay open

### Put here any screenshots or videos (optional)

![image](https://github.com/user-attachments/assets/b830604f-594c-4ba2-8653-649595d4f9c0)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I wil fix it by changing the close method on link click

**Comment by surajvast1** [comment]
Go on take it @Utsavladia

**Comment by Utsavladia** [comment]
@surajvast1 
Kindly reivew this

**Comment by Utsavladia** [comment]
@surajvast1 Kindly review this GSSOC is getting ended

**Comment by Utsavladia** [comment]
@PranavBarthwal 
Kindly merge this PR before GSSOC ends 😌
