### ISSUE TITLE
Enabaling hovering effect on navbar

### ISSUE THREAD

**Issue by Riya922003** [PranavBarthwal/cosmoXplore#50]
### Describe the feature

A hovering effect should be added to navbar .

### It should be implemented because

it should be implemnted because it would be easily visible to user that this component can be hovered and it is not a text 

### Additional context

I am a gssoc contributor I would like to  add this additional feature kindly assign me this issue 

### Would you like to work on this issue?

Yes

**Comment by PranavBarthwal** [comment]
This is a duplicate issue. Please find a new one.
I request you to review existing issues before submitting your own to prevent duplicates
Thanks
