### ISSUE TITLE
Redesigning the Complete navbar

### ISSUE THREAD

**Issue by AtharvKasar04** [PranavBarthwal/cosmoXplore#53]
### Describe the feature

The navbar needs to be redesigned so that it will blend in more properly and looks minimal and complementing the Clean overall look of the site.

### It should be implemented because

The current navbar has no special hover effects and as well as it needs a bit of text redesigning and a more design elements.

### Additional context

@PranavBarthwal Can you please assign me this issue under GSSoC'24. I will make the navbar look more awesome and well organized.

Thank You!

### Would you like to work on this issue?

Yes

**Comment by PranavBarthwal** [comment]
Go ahead @AtharvKasar04

**Comment by AtharvKasar04** [comment]
> it will be assigned toyou once you complete the other assigned issue @AtharvKasar04

Okay no issues sir. I'll do it :)

**Comment by mukulpythondev** [comment]
@PranavBarthwal  I can work on it please assign to me

**Comment by Ahmad102938** [comment]
@PranavBarthwal can you assign this issue sir I would like to work on this under gssoc24

**Comment by PranavBarthwal** [comment]
@mukulpythondev assigned to you. go ahead.
