### ISSUE TITLE
Autotype element overlapping

### ISSUE THREAD

**Issue by DikshaDhasmana** [PranavBarthwal/cosmoXplore#54]
### Describe your issue

In PC view, when the strings listed to be autotyped are untyped completely, the cursor moves upwards, moving the whole content below it upwards.

### Steps to reproduce the bug

https://github.com/PranavBarthwal/cosmoXplore/assets/123383817/5383d641-36f0-42b6-bb3f-74fbb60b631b

### Put here any screenshots or videos (optional)

In the above clip you can clearly see the content overlapping the line creating an awkward jerk effect.

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I have fixed the bug by replacing the string to those which have same first letter, X, ensuring that the below content doesnt overlap the line.

https://github.com/PranavBarthwal/cosmoXplore/assets/123383817/d4c677de-8c7d-4bfb-b70e-9274d6ee6d43

**Comment by DikshaDhasmana** [comment]
Kindly assign this issue to me under GSSOC label

**Comment by PranavBarthwal** [comment]
@DikshaDhasmana go ahead!
