### ISSUE TITLE
Adding chat bot 

### ISSUE THREAD

**Issue by nagamukesh** [PranavBarthwal/cosmoXplore#65]
### Describe the feature

a button on screen will open a chat bot to interact the user with

### It should be implemented because

As space is a very vast topic, one can have/get a doubt/query when he/she browses the web app and it can be cleared right away by the chat bot 
please assign me this issue under gssoc 2024

### Would you like to work on this issue?

Yes

**Comment by PranavBarthwal** [comment]
this is a duplicate issue.
