### ISSUE TITLE
Add social media Icons

### ISSUE THREAD

**Issue by Sibam-Paul** [PranavBarthwal/cosmoXplore#68]
### Describe the feature

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/158052549/9192dcf1-8344-4ebc-b021-9d11b32a8f84)

Want to add facebook , instagram , twitter , linkin social accounts at the bottom

### It should be implemented because
people will able to reach the Project admin

### Additional context
Please assign me this issue under GSSOC'24

### Would you like to work on this issue?
Yes

**Comment by Syed0206** [comment]
I would like to work on this issue @PranavBarthwal can you please assign me this issue under GSSOC'24

**Comment by Paavni-Goyal** [comment]
Hey, I would like to work on the same. Can you please assign this to me under GSSoC'24.

**Comment by Ahmad102938** [comment]
hello @PranavBarthwal can you assign this issue to me I would really like to work on this

**Comment by nishitasinghhh** [comment]
@PranavBarthwal  kindly assign this issue to me under GSSoC'24, I am willing to work on this

**Comment by Sibam-Paul** [comment]
@PranavBarthwal assign me this as fcfs
