### ISSUE TITLE
Adding more information in Readme file for new contributors.

### ISSUE THREAD

**Issue by astro-dally** [PranavBarthwal/cosmoXplore#7]
### Describe the bug

- [X] Information addition regarding the newest change through a PR.
- [ ] Typo error.
- [ ] New category addition.
- [ ] Refractoring sentences that make more sense.
- [ ] Fixing broken links.
- [ ] Refractors / reformating of the document.

### Additional Context

I want to help new contributors get started with the project. I'm thinking of adding simple instructions on how to fork, clone, and edit the code. @PranavBarthwal, can you assign this to me if you agree? Thanks!

**Comment by Dev-AyushTrivedi** [comment]
I am deeply fascinated by astronomy, cosmic phenomena, and space exploration. I am highly interested in contributing to this cosmos-themed website. Could you please assign this issue to me? I am participating in the GirlScript Summer of Code (GSSoC) 2024 and I believe this project aligns perfectly with my interests and skills. so, please assign this to me..
