### ISSUE TITLE
Extending the date in viewing mar rover imagery

### ISSUE THREAD

**Issue by divyalaldinani** [PranavBarthwal/cosmoXplore#70]
### Describe your issue

As the land date of rover is 2012-08-06, thus any date after that till 2024 can be a valid date to check mars image captured by rover.

### Steps to reproduce the bug

1. go to main page
2. on "mars rover imagery" section, check for input of date field

### What was the expected result?

the user should be able to be select dates from 06/08/2012 to 01/01/2024

### Put here any screenshots or videos (optional)

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/82147067/b78fd9b7-47a2-45f7-b743-8f570a49f907)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

by changing the beginning date in the input field in html file

**Comment by PranavBarthwal** [comment]
go ahead

**Comment by divyalaldinani** [comment]
what happened to this? https://pranavbarthwal.github.io/cosmoXplore/

**Comment by PranavBarthwal** [comment]
> what happened to this? https://pranavbarthwal.github.io/cosmoXplore/

A contributor's PR messed up with the UI. Fixed it.
