### ISSUE TITLE
The Astronomy Picture of the day section's UI is not good.

### ISSUE THREAD

**Issue by Abhishek-465** [PranavBarthwal/cosmoXplore#75]
### Describe your issue

The APOD section is not looking great.It need some adjustments in CSS. I can solve this problem and improve the UI of the section

### Steps to reproduce the bug

Open and scroll down to the astronomy picture of the day.

### What was the expected result?

The UI should be good. The contents should be aligned properly.

### Put here any screenshots or videos (optional)

![Screenshot (46)](https://github.com/PranavBarthwal/cosmoXplore/assets/127030695/ac4e1982-eff6-4484-853f-df86be0a3ba7)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I can solve this problem and improve the UI of the section by using CSS.
Working under GSSOC

**Comment by Abhishek-465** [comment]
Currently your whole website is broken due to someone's mistake.
![Screenshot (47)](https://github.com/PranavBarthwal/cosmoXplore/assets/127030695/ae38e891-acb4-4583-9d8d-af252d6cdc8b)
![Screenshot (48)](https://github.com/PranavBarthwal/cosmoXplore/assets/127030695/2cfbdb07-1dbb-4c2f-8a22-d369f9653230)
I can restore your website upto my previous commit and then work on the APOD section. Should i proceed?

**Comment by PranavBarthwal** [comment]
This is was fixed in some other PR. you may find some other issues to work upon.
Thanks

**Comment by Abhishek-465** [comment]
Okay thank you
