### ISSUE TITLE
To improve the responsiveness of the  ui in the "MARS ROVER IMAGERY" section in the  mobile view.

### ISSUE THREAD

**Issue by psychic-coder** [PranavBarthwal/cosmoXplore#76]
### Describe your issue

The description sticks out in the mars rover section so I would love to contribute on this project under GSSoC'24 .
<img width="557" alt="Screenshot 2024-05-12 at 3 34 03 AM" src="https://github.com/PranavBarthwal/cosmoXplore/assets/134062997/d5c4bc2b-70b6-42f4-a720-9e3d156f727f">

### Steps to reproduce the bug

Go the landing page,
Decrease the page size width to mobile view
scroll down to the "Mars rover" section

### What was the expected result?

The image will be in the middle (equally spaced from left and right ) and the text will be below it in the mobile view and in the desktop view it will remain as it is.

### Put here any screenshots or videos (optional)

<img width="557" alt="Screenshot 2024-05-12 at 3 34 03 AM" src="https://github.com/PranavBarthwal/cosmoXplore/assets/134062997/ac31306b-1ba8-431b-bbab-c4d0edbf94f9">

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I will fill this issue using the flex property and a bit of tailwind css.

**Comment by PranavBarthwal** [comment]
someone is already working on overall responsiveness.
You can find some other bug
