### ISSUE TITLE
Bug in Contact us form

### ISSUE THREAD

**Issue by pankaj-bind** [PranavBarthwal/cosmoXplore#78]
### Describe your issue

When you click on submit without even filling any details, it sends message. 

### Steps to reproduce the bug

1. Go to home page
2.  Scroll down to Contact us

### What was the expected result?

There must be certain condition that checks whether all details filled or not.

### Put here any screenshots or videos (optional)

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/73558583/680f4a60-8e41-49c3-9616-b8bf201e0d14)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I would write some scripts that validate if the user entered details or not and also it will check its validity.

**Comment by PranavBarthwal** [comment]
someone already working on this
