### ISSUE TITLE
Enter datebox broken

### ISSUE THREAD

**Issue by pankaj-bind** [PranavBarthwal/cosmoXplore#8]
### Describe your issue

When you reduce the screen size the input box and enter button both get separated.

### Steps to reproduce the bug

1) home page

### What was the expected result?

input box and button must me joined together.

### Put here any screenshots or videos (optional)

![tg](https://github.com/PranavBarthwal/cosmoXplore/assets/73558583/c6751979-f33b-4d76-bdff-f889b0caf1d1)

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I will place both input box and enter button inside a separate div and apply some css to fix it.
please assign me this task and label this as GSSoC'24.
![tg](https://github.com/PranavBarthwal/cosmoXplore/assets/73558583/36647c53-7a5d-4374-9dca-7e5ef9b803cf)

**Comment by PranavBarthwal** [comment]
@pankaj-bind thanks for raising this issue. 
The GSSoC '24 coding period will start from tomorrow, so I will assign it and add relevant labels tomorrow for sure.
