### ISSUE TITLE
Input of date is looks pale.

### ISSUE THREAD

**Issue by Anjaliavv51** [PranavBarthwal/cosmoXplore#83]
![image](https://github.com/PranavBarthwal/cosmoXplore/assets/154777864/ca8c7390-b733-4438-b778-c872777788e7)

I would like to make this more attractive , this looks like a stain in your website!!!
Could assign this to remove this stain on your website under GSSOC'24?

**Comment by Ahmad102938** [comment]
hello admin i would like to work on contact input and date input and assuring that it will more attractive

**Comment by PranavBarthwal** [comment]
go ahead

**Comment by Anjaliavv51** [comment]
Improvement of Date Input:

https://github.com/PranavBarthwal/cosmoXplore/assets/154777864/d01be4d2-00e5-402b-89cb-2224a691ec71

**Comment by Anjaliavv51** [comment]
Add labels to the PR #149

**Comment by Anjaliavv51** [comment]
## After Improvement

https://github.com/PranavBarthwal/cosmoXplore/assets/154777864/1d63a9d6-c3de-444a-9b31-80564232a40f

**Comment by Anjaliavv51** [comment]
their are some conflicts , it takes time to resolve.
