### ISSUE TITLE
Shock an amazing site isn't responsive???

### ISSUE THREAD

**Issue by Anjaliavv51** [PranavBarthwal/cosmoXplore#85]
### Describe the feature

[20240512-0719-35.5212798.zip](https://github.com/PranavBarthwal/cosmoXplore/files/15285390/20240512-0719-35.5212798.zip)
Resposive responsive!!!

### It should be implemented because

Would like to make resposive as , this site appearence is good!!!
It will be more good if it is responsive....

### Additional context

Assign this issue to me..
Thank You!!!

### Would you like to work on this issue?

Yes

**Comment by PranavBarthwal** [comment]
will be assigned to you once you complete the previously assigned issue

**Comment by Anjaliavv51** [comment]
Please merge the commits with name Update index.html & Update style.css
