### ISSUE TITLE
Closing Button for rover display section 

### ISSUE THREAD

**Issue by Chandu6702** [PranavBarthwal/cosmoXplore#87]
### Describe the feature

I will add an button with an event listener that can close the displayed content.

### It should be implemented because

when we click on enter button in "Display on entering date section" rover info is displayed but we are unable to close it. we have to refresh the site to close.

### Additional context

please assign this to me.

### Would you like to work on this issue?

Yes

**Comment by PranavBarthwal** [comment]
go ahead

**Comment by Chandu6702** [comment]
Thank You!!
