### ISSUE TITLE
Adding the mail Functionality 

### ISSUE THREAD

**Issue by Abhishek-465** [PranavBarthwal/cosmoXplore#9]
### Describe the feature

After sending the message i want to send an email to the owner's email. The frontend is already done, i want to implement its backend and make it working. Kindly assign me this issue.
Working under GSSOC 24

### It should be implemented because

It will add the real functionality.

### Would you like to work on this issue?

Yes

**Comment by PranavBarthwal** [comment]
@Abhishek-465 Thanks for raising this issue.
I'll surely assign this to you after 19:00 so that it gets counted under GSSoC'24.

**Comment by Pulkitxm** [comment]
Can I get assigned this issue, I have completed this already.

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me
@PranavBarthwal

**Comment by Danish0703** [comment]
plz assign this task to me
