### ISSUE TITLE
Typing Effect is Breaking the Word Wrap

### ISSUE THREAD

**Issue by DonaldReddy** [PranavBarthwal/cosmoXplore#90]
### Describe your issue

the Typing Effect is breaking the word wrap into new line and going back to previous line, which disturbs the user experience.
And the typing effect speed seems fast.

### Steps to reproduce the bug

1. Go to Home page
2. Observe the typing effect in the Hero section

### Put here any screenshots or videos (optional)

https://github.com/PranavBarthwal/cosmoXplore/assets/83972294/c7baad8f-eb5f-440f-86e5-ae08aca5e314

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I fix the word wrap breaking issue by making the typing effect start from the new line and making it remain on the same line.
Add i reduced the typing speed to improve the user experience.

**Comment by PranavBarthwal** [comment]
go ahead
