### ISSUE TITLE
Would like to add preloader?

### ISSUE THREAD

**Issue by Anjaliavv51** [PranavBarthwal/cosmoXplore#91]
### Describe the feature

Preloader to your website.

### It should be implemented because

coz website good it will goof if preloader is added.

### Additional context

I would like to make it enhance..
Please assign this repo under GSSOC 24....

### Would you like to work on this issue?

Yes

**Comment by PranavBarthwal** [comment]
Go ahead.
Also add preloader to apod image.
And mars rover section

**Comment by Anjaliavv51** [comment]
Okay

**Comment by Anjaliavv51** [comment]
Please merge the changes with commit names update index.html and update
style.css

**Comment by Anjaliavv51** [comment]
Please merge the changes with commit names update index.html and update
style.css
