### ISSUE TITLE
Using Nasa API add a section of earth satellite view of the users current location

### ISSUE THREAD

**Issue by Pratik2401** [PranavBarthwal/cosmoXplore#93]
### Describe the feature

To display a image of earth from satellite of the current persons location

![image](https://github.com/PranavBarthwal/cosmoXplore/assets/105542579/308056e1-e8d5-4cbc-9b8f-ae4435b1c4ed)
![Uploading image.png…]()

### Would you like to work on this issue?

Yes

**Comment by PranavBarthwal** [comment]
@Pratik2401 go ahead.
Create this feature in a new page, having same design language and color palette as the home page.
Make sure to create a new folder named `pages` inside that create another folder named `earth-satellite-view` where you can create its html, css and js files.
Happy Coding.
