### ISSUE TITLE
Incorrect string autotyping

### ISSUE THREAD

**Issue by DikshaDhasmana** [PranavBarthwal/cosmoXplore#99]
### Describe your issue

The strings being autotyped are incorrect, may be due to some unsynced pr merge.

### Steps to reproduce the bug

The bug is visible on the site's home page.

### Put here any screenshots or videos (optional)

https://github.com/PranavBarthwal/cosmoXplore/assets/123383817/c4144442-79b9-4c3a-9a73-495d8c6cd875

### Would you like to work on this issue?

Yes

### How will you fix this? (Only if you want to work on this issue)

I will fix the strings listed in the autotype function.

**Comment by PranavBarthwal** [comment]
lol! go ahead
